<form action="" method="post" name="addrouting" class="inputbox" >
<input type="hidden" id="barcode_id" name="barcode_id" value="<?php echo $this->Request['barcode_id'];?>">
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6>
			<?php if($this->Request['forwarder_id']==48){?>
			<?php echo $this->translate("Systematic Pickup Location");?>
			<?php }elseif($this->Request['addservice_id']==126){ ?>
			  <?php echo $this->translate("Parcel Location");?>
			<?php }?>
			</h6>
             
		  </div>
          <div class="row">
		    <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Name"); ?></label></div>
            <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="company_name" name="company_name" value="<?php echo $this->pickupdetails['company_name']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			 <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Street1"); ?></label></div>
			 <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="street1" name="street1" value="<?php echo $this->pickupdetails['street1']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			 <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Street2"); ?></label></div>
			  <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="street2" name="street2" value="<?php echo $this->pickupdetails['street2']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			 <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Zipcode"); ?></label></div>
			  <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="zipcode" name="zipcode" value="<?php echo $this->pickupdetails['zipcode']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			 <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("City"); ?></label></div>
			  <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="city" name="city" value="<?php echo $this->pickupdetails['city']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			
			  <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Country"); ?></label></div>
			 <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="country_id" name="country_id" value="<?php echo $this->pickupdetails['country_id']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
			 
			  <div class="col-sm-2 col_paddingtop">
			 <label><?php echo $this->translate("Phone"); ?></label></div>
			 <div class="col-sm-6 col_paddingtop">
				 <input type="text" id="phone" name="phone" value="<?php echo $this->pickupdetails['phone']?>" class="inputfield">
            </div>
			 <div class="clearfix"></div>
   <div class="clearfix"></div>
   <div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
      <div id="table"></div>
	  <div class="col-sm-6 col_paddingtop"> <input type="submit" name="pickup_address" value="Add Pickup" class="btn btn-danger btn-round"></div>
   </div>
</div>
</div>
</form>
