   
    <div class="tab-content">
      <form method="post" action="" class="inputbox" name="addadministrator" id="addadministrator">
	    
		<div id="table">
			<div class="header-row row">
				<span class="cell" style="text-align:center"><?php echo $this->translate("Add New Administrator");?></span>
			</div>
		</div>
		
		<!--<table width='70%' border="1" cellpadding="2" cellspacing="1" align="center">
			<tr>
				<td width="20%"><lable><b><?php echo $this->translate("Administrator's Type");?></b></lable></td>
				<td width="20%"><lable><?php echo $this->translate("Super Admin");?></lable></td>
			</tr>
			<tr>
				<td width="20%"><lable><b><?php echo $this->translate("Username");?></b></lable></td>
				<td width="20%"><input type="text" name="username" id="username" /></td>
			</tr>
			<tr>
				<td width="20%"><lable><b><?php echo $this->translate("Password");?></b></lable></td>
				<td width="20%"><input type="password" name="password" id="password" /></td>
			</tr>
			<tr>
				<td width="20%"><lable><b><?php echo $this->translate("Confirm Password");?></b></lable></td>
				<td width="20%"><input type="password" name="re-password" id="re-password" /></td>
			</tr>
		</table>-->
            
      </form>
    </div>