    <script src="<?php echo $this->baseUrl('public/js/account.js');?>"></script>
	
	<div id="table"><div class="header-row row">
		<span class="cell" style="text-align:left"><?php echo $this->translate("Edit Password");?></span> 
	</div></div>
	
	<div class="col-md-2"></div>
		<div class="col-md-8">
		<div style="text-align:center;color:#FF0000"><?php echo $this->translate("* Marked fields are mandatory");?></div> 
			<div id="table"><div class="header-row row">
				<span class="cell" style="text-align:center"><?php echo $this->translate("Change Password");?></span>
			</div>
	
		</div>		
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1">
					
					<?php echo $this->changepassword; ?>
				</div>
			</div>
		</div>
	<div class="col-md-2"></div>
	