    <script src="<?php echo $this->baseUrl('public/js/account.js');?>"></script>
	<script src="<?php echo $this->baseUrl('public/js/colorpicker.js');?>"></script>
	
	
	<div id="table"><div class="header-row row">
		<span class="cell" style="text-align:center"><h6><?php echo $this->translate("Customer");?></h6></span> 
	</div></div>
	
	<!--<div class="input-title"><?php echo $this->translate("Customer")?></div>-->
	
	<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
        <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <ul class="nav nav-tabs nav-justified">
                <li> <a href="customer"><?php echo $this->translate("List")?><i class="fa fa-folder"></i></a> </li>
                	<?php if($this->customeraction=='Add'){?>
						<li  class="active"> <a href="customerform"><?php echo $this->translate("Add Customer")?><i class="fa fa-ticket"></i></a> </li>
					<?php }else{ ?>	
						<li  class="active"> <a href="customerform?token=<?php echo $this->token;?>"><?php echo $this->translate("Edit Customer")?><i class="fa fa-ticket"></i></a> </li>
					<?php }?>	
				
              </ul>
			</div>
		</div>	
	</div>	
	
	
	<div class="col-md-2"></div>
		<div class="col-md-8">
		<div style="text-align:center;color:#FF0000"><?php echo $this->translate("* Marked fields are mandatory");?></div>
			<div id="table"><div class="header-row row">
			<?php if($this->customeraction=="Add"){?>
				<span class="cell" style="text-align:center"><?php echo $this->translate("Add New Customer");?></span>
			<?php }else{?>
				<span class="cell" style="text-align:center"><?php echo $this->translate("Edit Customer");?></span>
			<?php }?>		 
	</div></div>
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1">
					
					<?php echo $this->addeditcustomer; ?>
				
				</div>
			</div>
		</div>
	<div class="col-md-2"></div>