<div class="row row-broken">
	<div class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="../dashboard"><i class="fa fa-home"></i></a></li>
			<li><a href="index"><?php echo $this->translate("Account");?></a></li>
			<li class="active"><a href="customer"><?php echo $this->translate("Customer");?></a></li>
		</ol>
	</div>
</div>

	<div class="row decor-default p-email">
		<div class="input-title"><?php echo $this->translate("Customer List"); ?></div>
	</div>
	
		<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <ul class="nav nav-tabs nav-justified">
                <li class="active"> <a href=""><?php echo $this->translate("List");?><i class="fa fa-folder"></i></a> </li>
                <li> <a href="customerform"><?php echo $this->translate("Add customer");?><i class="fa fa-ticket"></i></a> </li>
              </ul>

	<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="customer" name="customer">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search Option")?></div>
				
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">

				<div class="clear-all"></div>
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="username" id="username" value="<?=$this->filteruser?>" class="input__field input__field--kaede" placeholder="User Name">
				<label for="username" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("Search User");?></span> </label>
				</span> </div>
				
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="company" id="company" value="<?=$this->filtercompany?>" class="input__field input__field--kaede" placeholder="Company Name">
				<label for="company" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("company");?></span> </label>
				</span> </div>
				
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="postcode" id="postcode" value="<?=$this->filterpostcode?>" class="input__field input__field--kaede" placeholder="PostCode">
				<label for="postcode" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("PostCode");?></span> </label>
				</span> </div>
				
				
				<div class="col-sm-2 col_paddingx10">
					<button class="btn btn-danger btn-round" name="search" type="submit" value="search"><?php echo $this->translate("Submit");?></button>
			  	</div>
				</div>
			</div>
			
		<!-- end filter -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row"> <span class="cell primary">#</span> <span class="cell"><?php echo $this->translate("Company");?></span> <span class="cell"><?php echo $this->translate("Email");?></span> <span class="cell"><?php echo $this->translate("Username");?></span> <span class="cell"><?php echo $this->translate("Password");?></span> <span class="cell"><?php echo $this->translate("name");?></span> <span class="cell"><?php echo $this->translate("Status");?></span> <span class="cell"><?php echo $this->translate("Action");?></span> 
					</div>
					<?php if(count($this->records)>0){
					
						foreach($this->records as $index=>$data){ //echo"<pre>";print_r($data);die;
							$status = ($data['user_status']=='1') ? 'Active' :  'Inactive';
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell primary" data-label="#"><?=$index+1?></span> 
							<span class="cell" data-label="Company"><?= $data['company_name']?></span> 
							<span class="cell" data-label="Email"><?= $data['email']?></span>
							<span class="cell" data-label="Username"><?= $data['username']?></span>
							<span class="cell" data-label="Password">test</span> 
							<span class="cell" data-label="Name"><?= $data['first_name'].' '.$data['last_name']?></span>
							<span class="cell" data-label="Status" id="statusSpan_<?=$index?>" ><?php if($data['user_status'] == "1") {  ?><img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=USERS?>','user_status','0','user_id','<?=$data['user_id']?>','<?=$index?>');" title="Change Status into In-Active" class="changeStatus" />
						<?php } else { ?>
						<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=USERS?>','user_status','1','user_id','<?=$data['user_id']?>','<?=$index?>');" title="Change Status into Active" class="changeStatus" />
						<?php } ?>
						</span>
						
							<span class="cell" data-label="Action">
							<div class="action-btns btn-group pull-right" role="group">
							  <a href='<?=$this->url(array('controller'=>'account','action'=>'customerform'),'default',  true).'?token='.Zend_Encript_Encription:: encode($data['user_id'])?>','60%','40%';"> <i class="fa fa-edit"></i></a>
							</div>
							</span> 
						</div><?php echo $this->paginator; ?>
					<?php }}else{?>
						<div class="row odd">
							<b><?=$this->translate("Recod not found !");?></b> 
						</div>
					<?php }?>	
				</div>
			</form>	
			</div></div></div>
			</div>
		</div>
	</div>
</div>
	
	