	<div id="table"><div class="header-row row">
		<span class="cell" style="text-align:center"><?php echo $this->translate("Driver All Settings");?></span> 
	</div></div>
	
	<div class="col-md-2"></div>
		<div class="col-md-8" >
			
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1" style="background-color:white;">
					<?php echo $this->driverconfig; ?>
				</div>
			</div>
		</div>
	<div class="col-md-2"></div>
	