	<div class="tab-content">

		 <div class="tab-pane fade in active" id="tab-1">



		<form method="post" action="" id="myprofile" name="myprofile">

		

		<!-- filter start -->

			<div class="filter">

				<div class="input-title"><?php echo $this->translate("My Profile")?></div>

				

				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">

				<div class="clear-all"></div>

				</div>

			</div>

			

		<!-- end filter -->

		

		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">

						

				<div id="table">

					<div class="header-row row"> <span class="cell primary"><?php echo $this->translate("Company");?></span> <span class="cell"><?php echo $this->translate("Email");?></span> <span class="cell"><?php echo $this->translate("Username");?></span> <span class="cell"><?php echo $this->translate("Password");?></span> <span class="cell"><?php echo $this->translate("Name");?></span> <span class="cell"><?php echo $this->translate("Status");?></span> <span class="cell"><?php echo $this->translate("Action");?></span> 

					</div>

					<?php if(count($this->records)>0){

					

						foreach($this->records as $index=>$data){ ?>

						<div class="row odd">

							<span class="cell" data-label="Company"><?= $data['company_name']?></span> 

							<span class="cell" data-label="Email"><?= $data['email']?></span>

							<span class="cell" data-label="Username"><?= $data['username']?></span>

							<span class="cell" data-label="Password"><?= $data['password_text'] ?></span>

							<!--<span class="cell" data-label="Password"><?=$this->translate('test');?></span> -->

							

							<span class="cell" data-label="Name"><?= $data['first_name'].' '.$data['last_name']?></span>

							

							<span class="cell" data-label="Status" id="statusSpan_<?=$index?>" ><?php if($data['user_status'] == "1") {  ?><img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=USERS?>','user_status','0','user_id','<?=$data['user_id']?>','<?=$index?>');" title="Change Status into In-Active" class="changeStatus" />

							<?php }else{ ?>

							<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=USERS?>','user_status','1','user_id','<?=$data['user_id']?>','<?=$index?>');" title="Change Status into Active" class="changeStatus" />

							<?php } ?>

							</span>

							

							<span class="cell" data-label="Action">

							<div class="action-btns btn-group pull-right" role="group">

							 

							  <a href='<?=$this->url(array('controller'=>'Account','action'=>'changepassword'),'default',  true).'?token='.Zend_Encript_Encription:: encode($data['user_id'])?>','60%','40%';"><img src="<?php print IMAGE_LINK; ?>/icon_password.gif" alt="" align="absmiddle" alt="Edit Password" title="Edit Password" border="0" class="changeStatus" /></i></a>

							  <?php if($this->ModelObj->Useconfig['level_id']==5){?>
&nbsp;|&nbsp; <a href='<?=$this->url(array('controller'=>'Senderaddress','action'=>'senderaddress'),'default',  true).'?token='.Zend_Encript_Encription:: encode($this->ModelObj->Useconfig['user_id'])?>','60%','40%';"> <i class="fa fa-book fa-2x" title="Sender Address"></i></a>

							    &nbsp;|&nbsp; <a href='<?=$this->url(array('controller'=>'Shopapi','action'=>'shopsetting'), 'default',  true).'?token='.Zend_Encript_Encription:: encode($this->ModelObj->Useconfig['user_id'])?>','60%','40%';"> <i class="fa fa-shopping-cart fa-2x" title="Shop Setting"></i></a>

							  <?php }?>

							</div>

							</span> 

						</div>

					<?php }}else{?>

							<div class="row odd">

								<b><?=$this->translate("Record not found !");?></b> 

							</div>

					<?php }?>	

				</div>

			</form>	

			</div></div></div>

			</div>

		</div>

	</div>

</div>

	

	