<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="customer" name="customer">
		
		<!-- filter start -->
		<div class="filter">
			<div class="input-title"><?php echo $this->translate("Pickup Request");?></div>
			
			<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">

				<div class="clear-all"></div>
				
				<div class="col-sm-3 col-sm-offset-9 col_paddingx10">
				<?php if($this->userconfig['level_id'] != 5){ ?>
				<span class="input input--kaede">
				 <select id='user_id' name='user_id' class="form-control" onchange="javascript:this.form.submit()">
				 <option>--<?=$this->translate("Select Customer")?>--</option>
				<?php 
				 
				foreach($this->customerList as $customer){ ?>
				  <option value="<?php echo $customer['user_id']; ?>">
				<?php
				  echo $customer['company_name'] . ", " . $customer['postalcode'] . ", " . $customer['city']; 
				}?>
				 </select>
				</span> 
				<?php } ?></div>
				
				
				</div>
			
		</div>
		<!-- filter ends -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><?php echo $this->translate("Customer Name");?></span> 
					<span class="cell"><?php echo $this->translate("Total Packet");?></span> 
					<span class="cell"><?php echo $this->translate("Total Weight");?>(KG)</span> 
					<span class="cell"><?php echo $this->translate("Create Date");?></span> 
					<span class="cell"><?php echo $this->translate("Pickup Time");?></span> 
					<span class="cell"><?php echo $this->translate("Pickup Date");?></span> 
					<span class="cell"><?php echo $this->translate("Pickup Address");?></span>
					<span class="cell"><?php echo $this->translate("Customer Address");?></span> 
					<span class="cell"><?php echo $this->translate("Pickup Request");?></span> 
										
					</div>
				<?php if(count($this->records)>0){
				
					foreach($this->records as $index=>$data){
						$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
					<div <?=$class?>>
						<span class="cell" data-label="Company"><?=($data['company']);?></span> 
						<span class="cell" data-label=""><?= $data['total_quantity']?></span>
						<span class="cell" data-label="Name"><?= $data['total_weight']?></span>
						<span class="cell" data-label="Name"><?= $data['create_date']?></span>
						<span class="cell" data-label="Name"><?= isset($data['pickup_time'])?$data['pickup_time']:'00-00-00'; ?></span>
						<span class="cell" data-label="Name"><?= $data['pickup_date']?></span>
						
						<span class="cell" data-label-""><?php echo str_replace("^", "<br>", $data['pickup_address']); ?>
						</span>
						<span class="cell" data-label="Name"><?= str_replace("^", "<br>", $data['customer_address'])?></span>
						
						<span class="cell" data-label="">
						</span>
						
					</div>
					

				<?php } 
				?> 
 			</div>
			
                                       <div class="odd">
					  <span class="col-xs-9"><?php echo commonfunction::paginator($this); ?>
					</div>
				<?php }else{?>
					
					<div class="odd">
						<span class="" ><b><?=$this->translate("Record not found !");?></b></span> 
					</div>
				<?php }?>	


			
					 	
			</form>	
			</div></div></div>