<?php 
if(isset($this->messages) && !empty($this->messages)){
	if($this->messages['status'] ==0)
	echo $this->MsgTemplateHelper()->render_msg_temp('layout/msgtemplate',$this->messages['message'],'danger','cancel');
}
?>
<?php  
		if(!empty($this->flashMessenger()->getMessages())){
			if($this->flashMessenger()->getMessages()[0]['type'] == "loggedout" || $this->flashMessenger()->getMessages()[0]['type'] == "loginfirst" )
			echo $this->MsgTemplateHelper()->render_msg_temp('layout/msgtemplate',$this->flashMessenger()->getMessages()[0]['msg'],'warning','flag');

		}
?>	
<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading"><?=$this->translate('Log in');?></div>
				<div class="panel-body">

					<?php $form = $this->form; 
					$form->prepare();
					$form->setAttribute('action',$this->url('admin/default',array('controller'=>'index','action'=>'index')));
					$form->setAttribute('autocomplete','off');
					echo $this->form()->openTag($form);?>
					 
						<fieldset>
							<div class="form-group">
								<?=$this->formRow($form->get('username')) ?>
								 
							</div>
							<div class="form-group">
								<?=$this->formRow($form->get('password')) ?>
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me"><?=$this->translate('Remember Me');?>
								</label>
							</div>
							<?=$this->formElement($form->get('submit')) ?>
						</fieldset>
						<?php echo $this->form()->closeTag($form); ?>
					 
				</div>
			</div>
		</div><!-- /.col-->
	</div><!-- /.row -->