<div class="content container-fluid">
    <div class="input-title"><?php echo $this->translate('Forward Message to Operator') ?></div>
</div>
<form id="forwardmessage" name="forwardmessage" class="inputbox" method="post">
    <div class="col-lg-12 col-md-12 col-sm-12 b-email">
        <div class="row">
		    <div class="col-sm-6 col_paddingtop">
			  <label for="operators" class="required"><?php echo $this->translate('Operators :') ?></label>
			  <?=$this->getHelper('HtmlSelect')->getSelect('operators',$this->operators,'user_id','company_name',Zend_Encript_Encription:: decode($this->Request['forward_to']),false,array('class'=>'inputfield')); ?>
			</div>
			<div class="clearfix"></div>
			<div class="col-sm-12 col_paddingtop">
		       <?php 
				require ROOT_PATH.'/public/fckeditor/FCKeditor.php';
				$var = new FCKeditor('message');
				$var->BasePath = BASE_URL.'/public/fckeditor/';
				$var->Height = '200px';
				$var->Weight = '200px';
				$var->Value = '';
				$var->Create();	
			   ?>
			</div>
			<div class="clearfix"></div>
            <div class="col-sm-12 col_paddingtop">
               <input type="submit" name="forwardmessage" value="Submit" class="btn btn-danger btn-round">
			</div>
		</div>
	</div>
</form>
