<div class="row row-broken">
    <div class="col-sm-12">
        <div class="tabs" id="seventh-tabs">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-1">
				    <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="col-sm-3 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="<?=BASE_URL ?>/Helpdesk/faqdetail" class=""><i class="fa fa-plus-square"></i><?php echo $this->translate("Question Details");?></a>
						</span></label>
					  </div>
					  <div class="clear-all"></div>
					  <div class="col-sm-9 col_paddingx10"><span class="input input--kaede"></span></div>
					</div>
					<?php $que_data = $this->quedetails; ?>
					<form method="post" name="addquestion" enctype="multipart/form-data">
					    <div class="col-sm-3 col_paddingtop">
						    <label for="questiontype"><b><?php echo $this->translate('Question Type:') ?></b></label>
						    <select name="que_type" id="que_type" class="inputfield">
							  <option value="1" <?php if($que_data['0']['question_type']=='1'){ echo 'selected="selected"'; } if($que_data['0']['question_type']!='1'){ echo 'disabled="disabled"'; }?>>FAQ Question</option>
							  <option value="2" <?php if($que_data['0']['question_type']=='2'){ echo 'selected="selected"'; } if($que_data['0']['question_type']!='2'){ echo 'disabled="disabled"'; }?>>Hepldesk Question</option>
							</select>
					    </div>
						<div class="clearfix"></div>
						<div class="col-sm-5 col_paddingtop" id="operators_div">
						  <label for="operators"><b><?php echo $this->translate('Operators') ?></b></label>
						    <select name="operators[]" class="inputfield" multiple="multiple">
                            <?php foreach($this->opertortype as $operatortype) {
                                $opertaors= commonfunction::explode_string($que_data['0']['operators']);
                                $selected = '';								
                                foreach($opertaors as $operator){
								  $selected .= ($operatortype['user_id']==$operator)? 'selected="selected"' : ''; 
								} 
								?>					
							  <option value="<?= $operatortype['user_id']; ?>" <?= $selected ?>><?=$operatortype['company_name']; ?></option>
							<?php } ?>
							</select>
						</div>
						<div class="clearfix"></div>
						<div class="col-sm-12 col_paddingtop" id="question_div">
						  <label for="question"><b><?php echo $this->translate('Question:') ?></b></label>
						  <?php 
						   require ROOT_PATH.'/public/fckeditor/FCKeditor.php';
						   $var = new FCKeditor('question');
						   $var->BasePath = BASE_URL.'/public/fckeditor/';
						   $var->Height = '200px';
						   $var->Weight = '100px';
						   $var->Value = $que_data['0']['question'];
						   $var->Create();	
						   ?>	
						</div>
						<div class="clearfix"></div>
						<div class="col-sm-12 col_paddingtop" id="answer_div">
						  <label for="answer"><b><?php echo $this->translate('Answer:') ?></b></label>
						  <?php 
						   require ROOT_PATH.'/public/fckeditor/FCKeditor.php';
						   $var = new FCKeditor('answer');
						   $var->BasePath = BASE_URL.'/public/fckeditor/';
						   $var->Height = '200px';
						   $var->Weight = '100px';
						   $var->Value = $que_data['0']['answer'];
						   $var->Create();	
						  ?>
						</div>
						<div class="clearfix"></div>
						<div class="col-sm-12 col_paddingtop">
						  <input type="submit" name="addquestion" value="update" class="btn btn-danger btn-round">
						</div>
						<div class="clearfix"></div>
					</form>
				</div>
            </div>
	    </div>
    </div>
</div>

<script>
$(document).ready(function(){
  $selected_val = $('#que_type').val();
  if($selected_val=='1'){
    $('#operators_div').hide();
  }
  else{
    $('#answer_div').hide();
  }
});

</script>