<div class="content container-fluid">
    <div class="input-title"><?php echo $this->translate('Mail Template') ?></div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 b-email">
    <div class="row">
		<div id="tablegrid">
			<table width="100%" border="0" id="claimstatus">
			<?php if(count($this->mailtemplate)>'0'){ ?>
			    <tr>
			      <td><b>Subject: <?= $this->mailtemplate['0']['subject'] ?></b></td>
				</tr>
				<tr>
				  <td><?= $this->mailtemplate['0']['email_text'] ?></td>
			    </tr>
			<?php } else{?>
			<tr>
			  <td><b>Please create template for <?=$this->templatename;?> notification!!</b></td>
			</tr>
			<?php } ?>
			</table>
		</div>
    </div>
</div>