<div class="content container-fluid">
    <form action="" method="post" name="specialPrice" id="specialPrice" class="inputbox">
<input type="hidden" id="routing_id" value="<?=$this->record['Routing']['routing_id']?>">
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Scpecial Price");?></h6>
          </div>
          <div class="row">
            <div class="col-sm-6 col_paddingtop">
			 <label><?php echo $this->translate("Port Name");?> : <b><?=$this->records['port_name']?></b></label>
			 </div>
			  <div class="col-sm-6 col_paddingtop">
			  <label><?php echo $this->translate("Customers");?></label>
			  <select class="inputfield" style="width: 150px;" id="user_id" name="user_id" onchange="$('#specialPrice').submit()">
			  <option value="">--<?php echo $this->translate("Select Customer");?>--</option>';
			  <?php	foreach($this->specialpricecustomer as $customers){ 
			        $selected  = ($this->Request['user_id']==$customers['user_id'])?'selected="selected"':'';
				  echo '<option value="'.$customers['user_id'].'" '.$selected.'>'.$customers['company_name'].'</option>';
				}
				?>
				</select>
			  </div>
				
   <div class="clearfix"></div>
   <div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
      <div id="table"><div class="header-row row">
	  	  <span class="cell"><?php echo $this->translate("Details");?></span>
	      <span class="cell"><?php echo $this->translate("Depot Prices");?></span>
		  <span class="cell"><?php echo $this->translate("Customer Prices");?></span>
		  <span class="cell"><?php echo $this->translate("Special Prices");?></span>
		  </div>
	  		 <div class="row">
		      <span class="cell" data-label="Price"><?php echo $this->translate("Prices");?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['depot_price']?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['customer_price']?></span>
			  <span class="cell" data-label="Depot"><input type="text" name="special_price" id="special_price" class="inputfield" value="<?php echo $this->records['special_price']?>"></span>
			  </div>
			  <div class="row">
		      <span class="cell" data-label="Import Surcharge"><?php echo $this->translate("Import Surcharge");?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['dep_import_surcharge']?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['cus_import_surcharge']?></span>
			  <span class="cell" data-label="Depot"><input type="text" name="import_surcharge" id="import_surcharge" class="inputfield" value="<?php echo $this->records['import_surcharge']?>"></span>
			  </div>
			  <div class="row">
		      <span class="cell" data-label="Destination Charge"><?php echo $this->translate("Destination Charge");?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['dep_destination_charge']?></span>
			  <span class="cell" data-label="Depot"><?php echo $this->records['cus_destination_surcharge']?></span>
			  <span class="cell" data-label="Depot"><input type="text" name="destination_surcharge" id="destination_surcharge" class="inputfield" value="<?php echo $this->records['destination_surcharge']?>"></span>
			  </div>
	  </div>
	  <div class="col-sm-2 col_paddingtop"> <input type="submit" name="btnsubmit" value="<?php echo $this->translate("Update");?>" class="btn btn-danger btn-round"></div>
   </div>
</div>
</div>
</form>
  </div>
 