<?php ini_set('display_errors',1); error_reporting(1); ?>

	<div class="input-title"><?php echo $this->translate("Depot Manager")?></div>
	
		<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <ul class="nav nav-tabs nav-justified">
            
                  <li><a href="<?php echo BASE_URL;?>/Depotnetwork/alldepotnetworkrouting/<?=$this->token;?>"><?php echo $this->translate("Depot Network List ")?><i class="fa fa-folder"></i></a></li>
                 
                <li  class="active"> <a href="<?php echo BASE_URL;?>/Depotnetwork/addeditdepotnetrouting/<?=$this->token;?>/add"><?php echo $this->translate("Add new Depot network Routing")?><i class="fa fa-ticket"></i></a> </li>
        
              </ul>
            

	<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="depotmanager" name="depotmanager">
					
				<div id="tablegrid">
					 <table width="100%" border="0" id="example">
					    <thead>
						<tr>
							<th><?=$this->translate('Company');?></th>
							<th><?=$this->translate('Country');?> </th>
							<th><?=$this->translate('Services');?></th>
							<th><?=$this->translate('Start Postcode => End PostCode => Scheduled Route');?></th>
							<th><?=$this->translate('Action');?></th>  
					</tr>
					</thead>
					
					<tbody>
					<?php
					if(count($this->records)>0){
						$i=0;
					 	foreach($this->records as $index=>$data){
						 	
						 	$class = ($i%2==0)?'even':'odd'; ?>
							<tr class="<?php echo $class;?>">
								<td width="15%" data-label="Company"><?php echo $data['company_name']; ?></td> 
								<td width="10%" data-label="Country"><?php echo $data['country_name']; ?></td>
								<td width="10%" data-label="Services">
									<?= $data['service_name']; ?>
								</td>
								<td width="20%" data-label="Start Postcodes">
									 <?=str_replace(array(',','-'), array('<br>','=>'), $data['postcodes']);?>
								</td>
								 
								<td width="10%" data-label="Action"><a href="<?=$this->url(array('controller'=>'Depotnetwork','action'=>'addeditdepotnetrouting'), 'default',  true).'/'.Zend_Encript_Encription:: encode($data['depot_id']).'/edit/'.Zend_Encript_Encription:: encode($data['dn_routing_id'])?>"  > 
						 			<i class="fa fa-edit fa-2x"></i>
								</a> | <a href="<?=$this->url(array('controller'=>'Depotnetwork','action'=>'deletedepotnetrouting'), 'default',  true).'/'.Zend_Encript_Encription:: encode($data['depot_id']).'/delete/'.Zend_Encript_Encription:: encode($data['dn_routing_id'])?>" onclick='return(confirm(" Are you sure you want to delete this"))'  > 
						 			<i class="fa fa-trash fa-2x"></i>
								</a>
								</td> 
								  
							</tr>
						<?php $i++; }   } else{ ?>
						<tr>
						  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>	
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td>&nbsp;</td>
						  </tr>
						<?php }
						?></tbody>
                     </table>
				</div>
			</form>	
			</div>
			</div>
			</div>
			</div>
		</div>
	
 	
	<script>
$(document).ready(function() {
  $('#example').DataTable( {
  "pageLength": 100,
  "lengthMenu": [[10, 25, 50, 100, 200, 500, -1], [10, 25, 50, 100, 200, 500, "All"]],
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
       column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>	