<div class="col-sm-3 col_paddingtop">
	<?php echo $this->postcode_start; ?>
</div>
<div class="col-sm-3 col_paddingtop">
	<?php echo $this->postcode_end; ?>
</div>
<div class="col-sm-4 col_paddingtop">
	<?php echo $this->sc_routing_id; ?>
</div>
<div class="col-sm-2 col_paddingtop">
	<!-- <span class="removeme" onclick="removethis(this)"> - Remove</span> -->
	<span class="lasticon"> <i class="fa fa-minus-square-o removeme" style="padding-top:15px;" onclick="removethis(this)"></i></span>
</div>