<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-6">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Status SMS Texts')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-2 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a onclick="openbox('<?=$this->url(array('controller'=>'Statuscode','action'=>'addstatussmstexts'),'default',  true)?>','60%','70%');" ><i class="fa fa-plus-square" aria-hidden="true"></i>
 							<?php echo $this->translate('Add SMS text')?></a></span></label>
					  </div>
					  
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>	
						 		<th><?=$this->translate('S No.');?></th>
								<th><?=$this->translate('Master Status');?></th>
								<th><?=$this->translate('Language');?> </th>
								<th><?=$this->translate('Notification Text');?> </th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>

						<tr class="<?php echo $class;?>">  
							
						</tr>

						</tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView();
} );
</script>