<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-6">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('SMS Setting for Status code')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-2 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="<?=$this->url(array('controller'=>'Statuscode','action'=>'smsreport'),'default',  true)?>"><i class="fa fa-plus-square" aria-hidden="true"></i>
 <?php echo $this->translate('SMS Report')?></a></span></label>
					  </div>
					  <div class="col-sm-2 col_paddingx10">
					  		<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="<?=$this->url(array('controller'=>'Statuscode','action'=>'allstatussmstexts'),'default',  true)?>"><i class="fa fa-plus-square" aria-hidden="true"></i>
 							<?php echo $this->translate('Status SMS Texts')?></a></span></label>
					  </div>
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>	
						 		<th><?=$this->translate('S No.');?></th>
								<th><?=$this->translate('Master Status');?></th>
								<th><?=$this->translate('Forwarder Days Check');?> </th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->errors)>0){
						 foreach($this->errors as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">  
						<td><?=$key+1 ?></td>
						<td><?= $data['status_name'] ?></td>
						<?php $smsdetail = $this->ModelObj->getsmsDetail($data['master_id']);//print_r($smsdetail); die; ?>
						<td><?php if(count($smsdetail)>0){foreach($smsdetail as $detail){
						echo $detail['forwarder_name'].' -- '.$detail['sms_days'].'<br>';
						} }else{echo '--';}?></td>
						<td width="8%" class="cell breadcrumb"><li><a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Statuscode','action'=>'editsmsdetail'),'default',  true).'?mode=edit&token='.Zend_Encript_Encription:: encode($data['master_id'])?>','60%','70%');">
						<i class="fa fa-edit"></i></a></li></td>
					  </tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data" colspan="6"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView();
} );
</script>