<div style="position: absolute; top:400px; right:0px; z-index:999999">
  <a href="javascript:void(0)" id="btn-filter1" title="Advance Search"><i class="fa fa-search fa-2x"></i></a>
</div>

<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="get" action="" id="filter_form" name="filter_form">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>				
				<div class="col-sm-3 col_paddingtop">
				<input type="text" name="search_word" id="search_word" placeholder="Search Word" class="inputfield">
				</div>
				<div class="col-sm-3 col_paddingtop">
					<input type="submit" class="btn btn-danger btn-round" name="search" id="search" value="Search">
				</div>
				<div class="clear-all"></div>
				<div class="col-sm-12 col_paddingtop"></div>
				 <!-- Advance Searchg --->			
	  <div class="cd-filter view-1" id="filter1">
          <h2><?php echo $this->translate("Advance Serach");?></h2>
          <a href="javascript:void(0)" class="cd-close">
          <svg>
            <use xlink:href="#icon-close"></use>
          </svg>
          </a>
           <div class="cd-filter-block">
              <h4><?php echo $this->translate("Country");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
				    <?php echo $this->getHelper('HtmlSelect')->getSelect('country_id',$this->filters['Country'],'country_id','country_code_name',(isset($this->Request['country_id'])?$this->Request['country_id']:''),false,array('class'=>'filter'));?> 
                </div>
                <!-- cd-select -->
              </div>
              <!-- cd-filter-content -->
            </div>
            <div class="cd-filter-block">
              <h4><?php echo $this->translate("Forwarder");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
                  <?php echo $this->getHelper('HtmlSelect')->getSelect('forwarder_id',$this->filters['Forwarder'],'forwarder_id','forwarder_name',(isset($this->Request['forwarder_id'])?$this->Request['forwarder_id']:''),false,array('class'=>'filter'));?> 
                </div>
                <!-- cd-select -->
              </div>
              <!-- cd-filter-content -->
            </div>
            <div class="cd-filter-block">
              <h4><?php echo $this->translate("From Date");?></h4>
              <div class="cd-filter-content" style="position:relative">
                <input type="text" name="from_date" id="from_date" value="<?php echo (isset($this->Request['from_date'])?$this->Request['from_date']:'')?>"">
              </div>
              <!-- cd-filter-content -->
            </div>
            <div class="cd-filter-block">
              <h4><?php echo $this->translate("To Date");?></h4>
              <div class="cd-filter-content" style="position:relative">
              <input type="text" name="to_date" id="to_date" value="<?php echo (isset($this->Request['to_date'])?$this->Request['to_date']:'')?>">
				<!-- cd-filter-content -->
				</div>
            </div>
            <div class="cd-filter-block">
              <h4><?php echo $this->translate("Customer");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
             <?php echo $this->getHelper('HtmlSelect')->getSelect('user_id',$this->filters['User'],'user_id','company_name',(isset($this->Request['user_id'])?$this->Request['user_id']:''),true,array('class'=>'filter'));?> 
			  </div>
                <!-- cd-select -->
              </div>
              <!-- cd-filter-content -->
            </div>
            <div class="cd-filter-block">
              <h4><?php echo $this->translate("Service");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
                 <?php echo $this->getHelper('HtmlSelect')->getSelect('service_id',$this->servicelist,'service_id','service_name',(isset($this->Request['service_id'])?$this->Request['service_id']:''),false,array('class'=>'filter'));?> 
					</div>
              </div>
            </div>
			 <div class="cd-filter-block">
              <h4><?php echo $this->translate("Added Type");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
				<?php echo $this->getHelper('HtmlSelect')->getSelect('shipment_type',$this->addedtype,'status_id','shipment_mode',(isset($this->Request['shipment_type'])?$this->Request['shipment_type']:''),false,array('class'=>'filter'));?> 
				</div>
              </div>
            </div>
			<div class="cd-filter-block">
              <h4><?php echo $this->translate("Print Status");?></h4>
              <div class="cd-filter-content">
                <div class="cd-select cd-filters">
				<?php echo $this->getHelper('HtmlSelect')->getSelect('print_status',array(array('print_id'=>1,'status'=>'Printed'),array('print_id'=>2,'status'=>'Not Printed')),'print_id','status',(isset($this->Request['print_status'])?$this->Request['print_status']:''),false,array('class'=>'filter'));?> 
				</div>
              </div>
            </div>
            <div class="clear-all"></div>
            <div style="padding:20px 0px; text-align:center">
			  <input type="submit" name="advance_search" id="advance_search" value="<?php echo $this->translate("Advance Search");?>" class="btn btn-warning btn-round"> 
            </div>
        </div>
		<!--End Advance Filter--->
				</div>
           </div>	
	 </form>
		<!-- end filter -->
<form method="post" action="" id="batch_checkin_form" name="batch_checkin_form">		
		<div class="col-sm-3 col_paddingtop">
		   <select name="shipment_mode" id="shipment_mode"  class="inputfield" onchange="javascript:if(this.value != '' && confirm('Selected shipment will Checked-In\nAre you sure?')) { $('#batch_checkin_form').submit(); }else{ return false;}">
			  <option value=""><?php echo $this->translate("With Selected");?></option>
			  <option value="1"><?php echo $this->translate("Batch Check-In");?></option>
			</select> </div>
			<div class="col-sm-4 col_paddingtop">
			<label><?php echo $this->translate("Bulk Check-In");?></label>
			<select name="shipment_mode1" id="shipment_mode1" class="inputfield" style="width:60%" onchange="javascript:if(this.value != '') this.form.submit(); else return false; ">
			  <option value=""><?php echo $this->translate("Checkin Option");?></option>
			  <option value="1000">---0 To 1000---</option>
			  <option value="2000">---0 To 2000---</option>
			  <option value="3000">---0 To 3000---</option>
			</select> 
			</div>
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row">
						<span class="cell"><input type="checkbox" id="check_uncheck_all" onchange="check_uncheckALL(this)"></span>
						<span class="cell"><?php echo $this->translate("Parcel Number");?></span> 
						<span class="cell"><?php echo $this->translate("No. of Parcel");?></span> 
						<span class="cell"><?php echo $this->translate("Customer");?></span> 
						<span class="cell"><?php echo $this->translate("Country");?></span> 
						<span class="cell"><?php echo $this->translate("Forwarder");?></span>
						<span class="cell"><?php echo $this->translate("Weight");?>(kg)</span> 
						<span class="cell"><?php echo $this->translate("Services");?></span> 
						<span class="cell"><?php echo $this->translate("Additional Service");?></span>
						<span class="cell"><?php echo $this->translate("Create Date");?></span> 
						<span class="cell"><?php echo $this->translate("Reference");?></span> 					
					</div>
					<?php 
					if($this->records['Total']>0){
						foreach($this->records['Records'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" <?php echo ($data['label_date']!='0000-00-00 00:00:00')?'style="background-color:green"':''?>><input type="checkbox" name="barcode_id[]" id="barcode_id<?= $data[BARCODE_ID]?>" value="<?= $data[BARCODE_ID]?>" class="check_uncheck_class"></span>
							<span class="cell" data-label="Barcode"><?=$data[BARCODE];?></span>
							<span class="cell" data-label="No. of Parcel">
							<?php 
								if ($data[QUANTITY]<=1) {
									$parcel_no = 1;
								} else {
								    $strchar = strrchr($data[REFERENCE], "-");
									$parcel_no = $strchar[1] + 1;
								}?>
							<?=$parcel_no.'/'.$data[QUANTITY]?></span>
							<span class="cell" data-label="Customer"><?=commonfunction::utf8Decode($this->ModelObj->CompanyName($data[ADMIN_ID]));?></span>
							<span class="cell" data-label="Country"><?=$data['country_name']?></span>
							<span class="cell" data-label="Forwarder"><?=$data['forwarder_name']?></span>
							<span class="cell" data-label="Weight"><?=$data[WEIGHT]?></span>
							<span class="cell" data-label="Service"><?=$data['service_name']?></span>
							<span class="cell" data-label="Add Service"><? ?></span>
							<span class="cell" data-label="Create Date"><?=$data['create_date']?></span>
							<span class="cell" data-label="Reference"><?=$data[REFERENCE]?></span>
							
						</div>
					<?php } } ?>
				</div>
					<div class="unit control">
                      <div class="nav-btns pull-right"> <?php echo commonfunction::PageCounter($this->records['Total'],$this->Request)?>
                      </div>
                    </div>
					 	
			</form>	
			</div></div></div>
<script>
$(function() {
		$( "#from_date" ).datepicker({
		  dateFormat: 'yy-mm-dd',
		  showOtherMonths: true,
		  selectOtherMonths: true
		});
		$( "#to_date" ).datepicker({
		  dateFormat: 'yy-mm-dd',
		  showOtherMonths: true,
		  selectOtherMonths: true
		});
	
	});
</script>			