<?php //print_r($this->acl);die; ?>

<?=$this->partial('layout/headerinner');?> 
<?=$this->partial('layout/nav');?> 
<?=$this->partial('layout/leftsidemenu');?> 


<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

<?php $this->MessagesHelper()->renderMsgsTemp('messages'); ?>
<?=$this->navigation('Customacl')->breadcrumbs()->setMinDepth(0)->setPartial('layout/partials/breadcrumbs'); ?>
	 

	<?=$this->content;?>

</div>	<!--/.main-->

<?=$this->partial('layout/footerinner');?> 
