  	 
  	<div class="row">
			<div class="col-lg-12 GlobalMessages">
					 
				<?php $messages = implode('<br><br>', $this->messages); ?>

				<?php if($this->type == 'success'){ ?>
					<div class="alert bg-success" role="alert"><em class="fa fa-lg fa-warning">&nbsp;</em> <?php echo $messages; ?> <a href="#" class="pull-right"><em class="fa fa-lg fa-close"></em></a></div>
				<?php } ?>	

				<?php if($this->type == 'danger'){ ?>

					<div class="alert bg-warning" role="alert"><em class="fa fa-lg fa-warning">&nbsp;</em> <?php echo $messages; ?> <a href="#" class="pull-right"><em class="fa fa-lg fa-close"></em></a></div>
				<?php } ?>	


				<?php if($this->type == 'error'){ ?>

					<div class="alert bg-danger" role="alert"><em class="fa fa-lg fa-warning">&nbsp;</em> <?php echo $messages; ?> <a href="#" class="pull-right"><em class="fa fa-lg fa-close"></em></a></div>
				<?php } ?>	

			</div>
		</div>		
		