<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="#"><?=$this->layout()->AdminSession->data['userRole']?></a>
				 <ul class="nav navbar-top-links navbar-right">
					 
					<li class="dropdown">
						<a href="<?=$this->url('admin/default',array('controller'=>'index','action'=>'logout'))?>"> 
					 		<button type="button" class="btn">
								<span >Logout</span>
					 		</button>
						</a>
					</li>
				</ul>  

				
			</div>
		</div><!-- /.container-fluid -->
	</nav>