<form action="" method="post" name="addcountry" class="inputbox" >
<input type="hidden" id="record_count" value="<?php echo count($this->totalclass)+1;?>">
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Add weight Class");?></h6>
          </div>
          <div class="row">
            <div class="col-sm-6 col_paddingtop">
			 <label><?php echo $this->translate("Country"); ?></label>
				 <select name="country_id[]" id="country_id" class="inputfield" multiple style="height:200px">
				<?php foreach($this->countrylist as $countrylist){
				  $selected = '';
				  if(isset($this->Request['country_id']) && $countrylist['country_id']==$this->Request['country_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $countrylist['country_id']?>" <?php echo $selected;?>><?php echo $countrylist['cncode'].'-'.$countrylist['country_name']?></option>
				<?php } ?>
              </select>
            </div>
		 <div class="col-sm-6 col_paddingtop">
			<label><?php echo $this->translate("Service"); ?></label>
				<select name="service_id[]" id="service_id" class="inputfield" multiple style="height:200px">
					<option value="">--<?php echo $this->translate("Service"); ?>--</option>
					<?php foreach($this->servicelist as $servicelist){
					  $selected = '';
					  if(isset($this->Request['service_id']) && $servicelist['service_id']==$this->Request['service_id']){
						$selected = 'selected="selected"';
					  }
					  $parent_service = (!empty($servicelist['parent_name']))?'<b>-'.$servicelist['parent_name'].'</b>':'';
					  ?>
					  <option style="border:1px  solid green; padding:2px;" value="<?php echo $servicelist['service_id']?>" <?php echo $selected;?>><?php echo $servicelist['service_name'].$parent_service?></option>
					<?php } ?>
				  </select>
				</div>
	 <div class="clearfix"></div>			
	<div class="col-sm-3 col_paddingtop">
			<label><?php echo $this->translate("Min weight"); ?></label>
			</div>
		<div class="col-sm-3 col_paddingtop">
			<label><?php echo $this->translate("Max Weight"); ?></label>
			</div>
		<div class="col-sm-3 col_paddingtop"></div>			
   <div class="clearfix"></div>
   <?php $i=1;?>
   <div id="weight_classes<?php echo $i;?>">
		 <div class="col-sm-3 col_paddingtop">
				<input type="text" name="min_weight[]" id="min_weight<?php echo $i;?>" class="inputfield">	
			</div>
		<div class="col-sm-3 col_paddingtop">
				<input type="text" name="max_weight[]" id="max_weight<?php echo $i;?>" class="inputfield">
			</div>
		<div class="col-sm-3 col_paddingtop">
		 <i class="fa fa-plus-square" onclick="addnewrow()"></i>
	  </div>	
	   <div class="clearfix"></div>
  </div> 
   <div class="col-sm-12 col_paddingtop">
            </div>
            <div class="col-sm-2 col_paddingtop"> <input type="submit" name="submit" value="Add Class" class="btn btn-danger btn-round"></div>
          </div>
        </div>
</form>
<script>
function addnewrow(){
    var count = parseInt($("#record_count").val()) + 1; 
	var row_content = '<div id="weight_classes'+count+'">';
	row_content += '<div class="col-sm-3 col_paddingtop">';
	row_content += '<input type="text" name="min_weight[]" id="min_weight'+count+'" class="inputfield"></div>';
	row_content += '<div class="col-sm-3 col_paddingtop">';
	row_content += '<input type="text" name="max_weight[]" id="max_weight'+count+'" class="inputfield"></div>';
	row_content += '<div class="col-sm-3 col_paddingtop">';
	row_content += '<i class="fa fa-minus-square-o" style="padding-top:15px;" onclick="removerow('+count+')"></i></div>';
	row_content += '<div class="clearfix"></div></div>';
	$("#weight_classes"+parseInt($("#record_count").val())).before(row_content);
	$("#record_count").val(parseInt(count));
}
function removerow(count){
    $("#weight_classes"+count).remove();
	$("#record_count").val(parseInt($("#record_count").val()) - 1);
}
</script>