<div class="content container-fluid">

    <form action="" method="post" name="specialPrice" id="specialPrice" class="inputbox">

<input type="hidden" id="routing_id" value="<?=$this->record['Routing']['routing_id']?>">

<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">

          <div class="b-email-title">

            <h6><?php echo $this->translate("Scpecial Price");?></h6>

          </div>

          <div class="row">

            <div class="col-sm-6 col_paddingtop">

			 <label><?php echo $this->translate("Destination Country");?> : <b><?=$this->record['Routing']['country_name']?></b></label><br>

			  <label><?php echo $this->translate("Depot");?> : <b><?=$this->record['Routing']['company_name']?></b></label>

			 </div>

			  <div class="col-sm-6 col_paddingtop">

			  <label><?php echo $this->translate("Customers");?></label>

			  <select class="inputfield" style="width: 150px;" id="user_id" name="user_id" onchange="$('#specialPrice').submit()">

			  <option value="">--<?php echo $this->translate("Select Customer");?>--</option>';

			  <?php	foreach($this->specialpricecustomer as $customers){ 

			        $selected  = (isset($this->Request['user_id']) && $this->Request['user_id']==$customers['user_id'])?'selected="selected"':'';

				  echo '<option value="'.$customers['user_id'].'" '.$selected.'>'.$customers['company_name'].'</option>';

				}

				?>

				</select>

			  </div>

				

   <div class="clearfix"></div>

   <div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">

      <div id="table"><div class="header-row row">

	      <span class="cell"><?php echo $this->translate("Services");?></span>

		  <span class="cell"><?=$this->record['Routing']['min_weight']?> - to - <?=$this->record['Routing']['max_weight']?></span>

		  </div>

	  

	     <?php foreach($this->record['Services'] as $routingservices){ ?>

			  <div class="row">

		      <span class="cell" data-label="Service"><?php echo $routingservices['service_name']?></span>

			  <span class="cell" data-label="Pricestep">

			  <?php echo $this->translate("Depot Price");?> : <input type="text" name="depotprice" value="<?php echo $routingservices['depot_price']?>" class="inputfield" readonly="readonly" style="width: 74px;" placeholder="Depot Price">&nbsp;

			  <?php echo $this->translate("Customer Price");?> : <input type="text" name="customerprice" value="<?php echo $routingservices['customer_price']?>" class="inputfield" readonly="readonly" style="width: 74px;" placeholder="Customer Price">&nbsp;

			  <?php if(isset($this->Request['user_id'])){ echo $this->translate("Special Price");?> : <input type="text" name="routingdata[<?php echo $routingservices['service_id']?>][<?php echo $routingservices['routing_id']?>][price]" value="<?php echo isset($this->specialprice[$routingservices['service_id']][$routingservices['routing_id']])?$this->specialprice[$routingservices['service_id']][$routingservices['routing_id']]:''?>" class="inputfield" style="width: 74px;" placeholder="Price">&nbsp;<?php } ?>

			 <input type="hidden" name="routingdata[<?php echo $routingservices['service_id']?>][<?php echo $routingservices['routing_id']?>][service_id]" value="<?php echo $routingservices['service_id']?>">

			 <input type="hidden" name="routingdata[<?php echo $routingservices['service_id']?>][<?php echo $routingservices['routing_id']?>][routing_id]" value="<?php echo $routingservices['routing_id']?>">&nbsp;

			 </span>

			  </div>

		 <?php } ?>

	  </div>

	  <div class="col-sm-2 col_paddingtop"> <input type="submit" name="btnsubmit" value="<?php echo $this->translate("Update");?>" class="btn btn-danger btn-round"></div>

   </div>

</div>

</div>

</form>

  </div>

 