
<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-6">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Product List')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-2 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Supplies','action'=>'addeditshopproduct'),'default',  true).'?mode=add'?>','60%','80%');"><i class="fa fa-plus-square" aria-hidden="true"></i>
<?php echo $this->translate('Add New Product')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('Product Name');?></th>
								<th><?=$this->translate('Product Description');?> </th>
								<th><?=$this->translate('Price');?></th>
								<th><?=$this->translate('Added Date');?></th>
								<th><?=$this->translate('Image');?></th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->Productlist)>0){
						 foreach($this->Productlist as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
						<td data-label="Product Name"><?=$this->translate($data['product_name']); ?></td> 
                        <td data-label="Product Description"><?=$this->translate($data['product_desc']); ?></td> 
						<td data-label="Price"><?=$this->translate($data['price']); ?></td>
						<td data-label="Added Date"><?=$this->translate($data['added_date']); ?></td>
						<?php $imgPath = (!empty($data['image']) && file_exists(ROOT_PATH."/public/webshop_product/thumbs/".$data['image'])) ? $data['image'] :'no_image.jpg';
							$specialPriceWindow = $this->url(array('controller' => 'Supplies','action'=>'specialprice','token'=>Zend_Encript_Encription:: encode($data['product_id'])),'default',true);
						?>
						<td data-label="Image"><img src="<?=BASE_URL.'/public/webshop_product/thumbs/'.$imgPath?>" height="50" width="50"/></td>
						
						<td data-label="Action">
							<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Supplies','action'=>'addeditshopproduct'),'default',  true).'?mode=edit&id='.Zend_Encript_Encription:: encode($data['product_id'])?>','60%','80%');">
							<i class="fa fa-edit"></i></a>|<a href="javascript:void(0);" onClick="deleterecord('<?=WEBSHOP_PRODUCTS?>','isDelete','1','product_id','<?=$data['product_id']?>');">
							<i class="fa fa-trash" title="Delete Product"></i></i></a>
							</td>
						</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data" colspan="7"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView();
} );
</script>