<style>
.org_button {
    background: none repeat scroll 0% 0% #004FA3;
    border: 1px solid #004FA3;
    color: #FFF;
    padding: 5px 10px;
    cursor: pointer;
}
.imgloading{position: absolute; background: rgb(0, 0, 0) none repeat scroll 0% 0%; opacity: 0.5; top: 0px; right: 0px; width: 100%; height: 100%; text-align: center;}
.imgloading img{margin-top:25px}
</style>
<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-6">
					<form method="post" action="">
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Your Shopping Cart Detail')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
					<div  id="tablegrid">
					 			<form  action="" method="post" name="addorder" id="addorder">
								<div id="cart"><?=$this->cartitems?></div>
								</form>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
 
 $(function() {
		$.buy = function(prd) {
			$.ajax({
				type : 'post',
				url: '<?=$this->url(array('controller'=>'Supplies','action'=>'addtocart'),'default',true)?>',
				data : 'token='+prd,
				
				success : function(resp){//alert(resp);return false;
					$('#cartitem').html(resp);
				}
			});
		}
	});

	function PriceWindowopen(url){
	$.fancybox({
			"width": "60%",
			"height": "90%",
			"autoScale": true,
			"transitionIn": "fade",
			"transitionOut": "fade",
			"type": "iframe",
			"href": url
		});
	}
	
	function editdatashow(value,count) {
		if(value=='Y'){
			$("#showquan"+count).hide();
			$("#editquan"+count).show();
			$("#qantity"+count).select();
		}
		if(value=='N'){
			$("#showquan"+count).show();
			$("#editquan"+count).hide();
		}
	}
	
	function savedata(count) {
		var token = $("#token"+count).val();
		var quantity = $("#qantity"+count).val();
		if($.isNumeric(quantity) == false || quantity == '0'){
			alert("Quantity should be number and greater than zero !!");
			 return false;
		}
		if(token != '' && quantity != '') {
			$.ajax({
				type: "post",
				url: '<?=$this->url(array('controller'=>'Supplies','action'=>'updatecart'),'default',true)?>',
				data: "token="+token+"&quantity="+quantity+"&update=order",
				
				beforeSend : function() {
				  $("#loader_"+count).show();
				 },
				
				success: function(msg){
					$("#loader_"+count).hide();
					$("#cart").html(msg);
				}
			});
		}
	}
	
	function deletedata(count) {
		var token = $("#token"+count).val();
		
		if(token != '') {
			if(confirm("Are you sure want to delete this article !")){
				$.ajax({
					type: "post",
					url: '<?=$this->url(array('controller'=>'Supplies','action'=>'updatecart'),'default',true)?>',
					data: "token="+token+"&update=order",
					success: function(msg){ //alert(msg);
						$("#cart").html(msg);
					}
				});
			}
		}
	}
	
	function continueshop() {
		location.href="<?php echo $this->url(array('controller' => 'Supplies','action'=>'productshop'),'default',true)?>";
	}
 </script>