
	<div class="row row-broken">
        <div class="col-sm-12">
				 <div class="filter">
				<div class="input-title"><?php echo $this->translate('Import Shipment')?></div>
			<div class="clear"></div>
				<div style="background:#ffffff; padding:10px; overflow:auto;text-align:center">
				<div class="clear-all"></div>
			<div class="col-sm-2">&nbsp;</div>	
			<div class="col-sm-8">
			  &nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'Shipment','action'=>'importsample'),'default',true)?>"><i class="fa fa-download"></i>&nbsp;&nbsp;<?php echo $this->translate("Download CSV Sample");?></a>
			  &nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'Shipment','action'=>'importlist'),'default',true);?>"><i class="fa fa-file-text-o"></i>&nbsp;&nbsp;<?php echo $this->translate("Import Shipment List");?></a>
			  &nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'Shopapi','action'=>'shopimport'),'default',true);?>"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;<?php echo $this->translate("Import From Shop");?></a>
			</div>
			<div class="col-sm-2">&nbsp;</div>	
			<div class="clear-all"></div>
				<div class="col-sm-2">&nbsp;</div>
					<div class="col-sm-8">
				<form id="Importshipmentform" class="inputbox" enctype="multipart/form-data" action="" method="post" onsubmit="return importvalidate()">	
					<table class="tbl_new">
					<tbody>
					<tr id="file_error" style="display:none;color:red;"></tr>
					<tr><th colspan="2"><?php echo $this->translate('Import')?></th></tr>
					 <?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==4 || $this->ModelObj->Useconfig['level_id']==6){?>
					 <tr>
						<td style="text-align:center"><?php echo $this->translate('Select Customer')?></td>
						<td style="width:450px"><?php echo $this->getHelper('HtmlSelect')->getSelect('user_id',$this->customerlist,'user_id','company_name','',true,array('class'=>'inputfield'));?> 
						</td>
					 </tr>
					  <?php } else{ 
					 $user_id = ($this->ModelObj->Useconfig['level_id']==10)?$this->ModelObj->Useconfig['parent_id']:$this->ModelObj->Useconfig['user_id'];
					 ?>
					 <input type="hidden" name="user_id" id="user_id" value="<?php echo Zend_Encript_Encription::encode($user_id)?>">
					 <?php } ?>
					 <tr>
						<td colspan="2"><input style="margin:auto" type="file" name="import_file" id="import_file"></td>
					</tr>
					<tr>
						<td style="text-align:right"><input type="submit" name="import" id="import" value="Import" class="btn btn-danger" style="width:40%;margin:auto"></td>
						<td style="text-align:left"><input type="submit" name="importwithHeader" id="importwithHeader" value="ImportWithHeader" class="btn btn-danger" style="width:60%;margin:auto"> 
						</td>
					 </tr>
					</tbody>
					</table>
				</form>	
					</div>
					<div class="col-sm-2">&nbsp;</div>
					<div class="clear-all"></div>
				</div>
			</div>
        </div>
	</div>
<script>
function importvalidate(){
   var user_id = $('#user_id').val();
   var files = $('#import_file').val();
   var ext = files.split('.').pop().toLowerCase();
  if(ext!='csv'){
	  $('#file_error').html('<td colspan="2">Only CSV file allowed</td>');
	  $('#file_error').show();
	  setTimeout("$('#file_error').hide();",5000);
	  return false;
  }else if(user_id==''){
      $('#file_error').html('<td colspan="2">Please Customer</td>');
	  $('#file_error').show();
	  setTimeout("$('#file_error').hide();",5000);
	  return false;
   }else{
	 $('#file_error').html('');
	  $('#file_error').hide();
	  return true;
   }   
}
</script>	
