
<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="print_label" name="print_label">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-2 col_paddingtop">
				<label><?php echo $this->translate("Country");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('country_id',$this->countrylist,'country_id','country_code_name',(isset($this->Request['country_id'])?$this->Request['country_id']:''),false,array('class'=>'inputfield'));?>
				</div>
				<?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11){?>
				<div class="col-sm-3 col_paddingtop">
				<label><?php echo $this->translate("Depot");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('parent_id',$this->depotlist,'user_id','company_name',(isset($this->Request['parent_id'])?$this->Request['parent_id']:''),true,array('class'=>'inputfield'));?>
				</div>
				<?php } ?>
				<?php if($this->ModelObj->Useconfig['level_id']!=5){?>
				<div class="col-sm-3 col_paddingtop">
				<label><?php echo $this->translate("Customer");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('parent_id',$this->depotlist,'user_id','company_name',(isset($this->Request['parent_id'])?$this->Request['parent_id']:''),true,array('class'=>'inputfield'));?>
				</div>
				<div class="col-sm-2 col_paddingtop">
				<label><?php echo $this->translate("Forwarder");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('parent_id',$this->depotlist,'user_id','company_name',(isset($this->Request['parent_id'])?$this->Request['parent_id']:''),true,array('class'=>'inputfield'));?>
				</div>
				<?php  } ?>
				<div class="col-sm-2 col_paddingtop">
					<input type="submit" class="btn btn-danger btn-round" name="search" id="search" value="Search">
				</div>
				<div class="clear-all"></div>
				<div class="col-sm-12 col_paddingtop"></div>
				</div>
		</div>
		<!-- end filter -->
		<div class="col-sm-3 col_paddingtop">
		<select name="shipment_mode" id="shipment_mode"  class="inputfield" onchange="javascript:if(this.value == 'Delete' &amp;&amp; confirm('Selected shipment will be deleted\nAre you sure?') || this.value == 'Print' || this.value == 'Move') $('#print_label').submit(); else if(this.value == 'PrintAll' &amp;&amp; label_option == 'a4') jQuery('#dialog').dialog('open'); else return false;">
			  <option value=""><?php echo $this->translate("With Selected");?></option>
			  <option value="Delete"><?php echo $this->translate("Delete");?></option>
			  <option value="Print"><?php echo $this->translate("Print");?></option>
			  <option value="Move"><?php echo $this->translate("Move to New Shipment");?></option>
		</select> </div>
		<div class="col-sm-2 col_paddingtop">
				<select name="shipment_mode1" id="shipment_mode1" class="inputfield" onchange="javascript:if(this.value != '') this.form.submit(); else return false; ">
				  <option value=""><?php echo $this->translate("Bulk Print");?></option>
				  <option value="1000">---0 To 1000---</option>
				  <option value="2000">---0 To 2000---</option>
				  <option value="3000">---0 To 3000---</option>
				</select> 
				</div>
				<div class="col-sm-2 col_paddingtop">
					<input type="text" name="change_weight" id="change_weight" class="inputfield" placeholder="Change Weight">
				</div>
				<div class="col-sm-2 col_paddingtop">
					<?php echo $this->getHelper('HtmlSelect')->getSelect('change_service_id',$this->serviceList,'service_id','service_name','',false,array('class'=>'inputfield'));?>
				</div>
				<div class="col-sm-2 col_paddingtop">
					<input type="submit" class="btn btn-danger btn-round" name="change" id="change" value="Update">
				</div>	
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><input type="checkbox" id="check_uncheck_all" onchange="check_uncheckALL(this)"></span> 
					<span class="cell"><?php echo $this->translate("Receiver");?></span> 
					<span class="cell"><?php echo $this->translate("Reference");?></span> 
					<span class="cell"><?php echo $this->translate("Country");?></span> 
					<span class="cell"><?php echo $this->translate("Postalcode");?></span> 
					<span class="cell"><?php echo $this->translate("Forwarder");?></span> 
					<span class="cell"><?php echo $this->translate("Quantity");?></span> 
					<span class="cell"><?php echo $this->translate("Weight");?></span>
					<span class="cell"><?php echo $this->translate("Service");?></span> 
					<span class="cell"><?php echo $this->translate("Sub-Service");?></span>
					<span class="cell"><?php echo $this->translate("Create Date");?></span>
					<span class="cell"><?php echo $this->translate("Action");?></span>				
					</div>
					<?php if($this->importlist['Total']>0){
					
						foreach($this->importlist['Records'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" data-label="ID"><input type="checkbox" name="shipment_id[]" id="shipment_id_<?= $data[SHIPMENT_ID]?>" value="<?=$data[SHIPMENT_ID];?>" class="check_uncheck_class"></span>
							<span class="cell" data-label="Country"><?=$data[RECEIVER];?></span>
							<span class="cell" data-label="REFERENCE"><?= $data[REFERENCE]?></span>
							<span class="cell" data-label="Country"><?= $data['country_name']?></span>
							<span class="cell" data-label="Zipcode"><?=$data[ZIPCODE]?></span>
							<span class="cell" data-label="Forwarder"><?=$data['forwarder_name']?></span>
							<span class="cell" data-label="Quantity"><?=$data[QUANTITY]?></span>
							<span class="cell" data-label="Weight"><?=$data['weight']?></span>
							<span class="cell" data-label="Service"><?=$data['service_name']?></span>
							<span class="cell" data-label="Add Service"><?=($data['addservice_id']>0)?$this->ModelObj->ServiceName($data['addservice_id']):'';?></span>
							<span class="cell" data-label="Create Date"><?=date('F- d, Y',strtotime($data['create_date']))?></span>
							<span class="cell" data-label="Action">
							
							<a href="javascript:void(0);"  onclick="if(confirm('Selected shipment will be deleted\nAre you sure?')){$('#shipment_id_<?= $data[SHIPMENT_ID]?>').prop('checked',true);$('#shipment_mode').val('Delete');$('#print_label').submit();}"><img src="<?=IMAGE_LINK.'/delete.png'?>" title="Delete"></a></span>
		
							</span> 
						</div>
					<?php }}else{?>
						
						<div class="row odd">
							<span class="cell" colspan="6"><b><?=$this->translate("Recod not found !");?></b></span> 
						</div>
					<?php }?>	

				</div>
				<div class="unit control">
				  <div class="nav-btns pull-right"> <?php echo commonfunction::PageCounter($this->importlist['Total'],$this->Request)?>
				  </div>
				</div>	 	
			</form>	
			</div></div></div>
<script>
function Addrouting(){
   var user_id = $('#user_id').val();
   if(user_id>0){
       openbox('<?php echo $this->url(array('controller'=>'Routing','action'=>'addrouting'),'default',true);?>?user_id='+user_id,'70%','90%');
   }else{
     alert('Please select Depot first');return false;
   }
}
function Editrouting(url){
    openbox(url,'70%','90%');
}
</script>			