<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="customer" name="customer">
			<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Customer");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('user_id',$this->customerlist,'user_id','company_name',(isset($this->Request['user_id'])?$this->Request['user_id']:''),true,array('class'=>'inputfield','style'=>"width:60%"));?> 
				</div>
				<div class="col-sm-4 col_paddingtop">
				  <button class="btn btn-danger btn-round" name="search" type="submit" value="search">Submit</button>
				</div>
				<div class="clear-all"></div>
				<div class="col-sm-12 col_paddingtop"></div>
				
				</div>
           </div>	
	<!-- end filter -->
		
		<div class="clear-all"></div>
		&nbsp;<a href="<?=$this->url(array('controller'=>'Shipment','action'=>'showallparcel'),'default',  true)?>"><i class="fa fa-eye"></i><?php echo $this->translate('Show All Parcel')?></a>
					
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><?php echo $this->translate("Company Name");?></span> 
					<span class="cell"><?php echo $this->translate("Total Shipment");?></span> 
					<span class="cell"><?php echo $this->translate("Total Quantity");?></span> 
					<span class="cell"><?php echo $this->translate("Total Weight");?>(KG)</span> 
					<span class="cell"><?php echo $this->translate("Total Price");?></span> 
					<span class="cell"><?php echo $this->translate("Action");?></span> 
					</div>
					<?php if($this->records['Total']>0){
					
						foreach($this->records['Records'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" data-label="Company"><a href="javascript:void(0)" onclick="openbox('<?=$this->url(array('controller'=>'Shipment','action'=>'viewshipment'),'default',true).'?user_id='.Zend_Encript_Encription::encode($data['user_id']);?>','90%','100%')"><?= $data['company_name']?></a></span> 
							<span class="cell" data-label="Email"><?= $data['Total_parcel']?></span>
							<span class="cell" data-label="Username"><?= $data['total_quantity']?></span>
							<span class="cell" data-label="Name"><?= $data['Total_weight']?></span>
							<span class="cell" data-label="Name"><?= $data['Total_weight']?></span>
							<div class="action-btns btn-group pull-right" role="group">
							  <a href="javascript:void(0)" onclick="openbox('<?=$this->url(array('controller'=>'Shipment','action'=>'viewshipment'),'default',true).'?user_id='.Zend_Encript_Encription::encode($data['user_id']);?>','90%','100%')"><button type="button" class="btn btn-default"><i class="fa fa-eye" title="View"></i></button></a>
							</div>
							</span> 
						</div>
					<?php }}else{?>
						
						<div class="row odd">
							<b><?=$this->translate("Recod not found !");?></b> 
						</div>
					<?php }?>	
				</div>
				<div class="unit control">
                      <div class="nav-btns pull-right"> <?php echo commonfunction::PageCounter($this->records['Total'],$this->Request)?>
                      </div>
                    </div>
					 	
			</form>	
			</div></div></div>