<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">
		<form method="post" action="" id="filter_form" name="filter_form">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Address Book");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="Name" id="Name" value="<?=isset($this->Request['Name'])?$this->Request['Name']:''?>" class="input__field input__field--kaede" placeholder="<?php echo $this->translate("Receiver Name");?>">
				<label for="Name" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("Name");?></span> </label>
				</span> </div>
				
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="postalcode" id="postalcode" value="<?=isset($this->Request['postalcode'])?$this->Request['postcode']:''?>" class="input__field input__field--kaede" placeholder="<?php echo $this->translate("PostCode");?>">
				<label for="postalcode" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("PostlCode");?></span> </label>
				</span> </div>
				<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede">
				<input type="text" name="city" id="city" value="<?=isset($this->Request['city'])?$this->Request['city']:''?>" class="input__field input__field--kaede" placeholder="<?php echo $this->translate("City");?>">
				<label for="city" class="input__label input__label--kaede"> 
				<span class="input__label-content input__label-content--kaede"><?php echo $this->translate("City");?></span> </label>
				</span> </div>
				<div class="col-sm-3 col_paddingx10">
				<select name="country_id" id="country_id" class="inputfield">
			    <option value="">--<?php echo $this->translate("Country"); ?>--</option>
				<?php foreach($this->countrylist as $countrylist){
				  $selected = '';
				  if(isset($this->Request['country_id']) && $countrylist['country_id']==$this->Request['country_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $countrylist['country_id']?>" <?php echo $selected;?>><?php echo $countrylist['cncode'].'-'.$countrylist['country_name']?></option>
				<?php } ?>
              </select>
				</div>
				
				<div class="col-sm-2 col_paddingx10">
					<button class="btn btn-danger btn-round" name="search" type="submit" value="search"><?php echo $this->translate("Search");?></button>
			  	</div>
				</div>
			</div>
		<!-- end filter -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><?php echo $this->translate("Receiver");?></span> 
					<span class="cell"><?php echo $this->translate("Country");?></span> 
					<span class="cell"><?php echo $this->translate("PostalCode");?></span> 
					<span class="cell"><?php echo $this->translate("City");?></span> 
					<span class="cell"><?php echo $this->translate("Street");?></span> 
					<span class="cell"><?php echo $this->translate("Email");?></span> 			
					</div>
					<?php 
					if(count($this->records)>0){
						foreach($this->records as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';
							$address = commonfunction::implod_array($data,'^');
							?>
						<div <?=$class?>>
							<span class="cell" data-label="Receiver Name"><a onclick="filladdress('<?php echo $address; ?>');" href="javascript:void(0)"><?=commonfunction::utf8Decode(commonfunction::strip_slashes($data['name']));?></a></span>
							<span class="cell" data-label="Country"><?=$data['country_name']?></span>
							<span class="cell" data-label="Postal_code"><?= $data['postalcode']?></span>
							<span class="cell" data-label="City"><?=commonfunction::strip_slashes($data['city'])?></span>
							<span class="cell" data-label="Street"><?= $data['street']?></span>
							<span class="cell" data-label="Email"><?=$data['email']?></span>
						</div>
					<?php } } else{?>	
						<div class="row odd">
							<span class="cell" colspan="6"><b><?=$this->translate("Recod not found !");?></b></span> 
						</div>
					<?php }?>	
				
				</div>
					 	
			</form>	
			</div></div></div>
			
<script>


</script>			
			