
<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">
			<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<form method="get" action="" id="filter_form" name="filter_form">
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Country");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('country_id',$this->countrylist,'country_id','country_code_name',(isset($this->Request['country_id'])?$this->Request['country_id']:''),false,array('class'=>'inputfield','style'=>"width:60%"));?> 
				</div>
				<?php if(in_array($this->ModelObj->Useconfig['level_id'],array(1,4,6))){?>
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Forwarder");?></label>
				<?php echo $this->getHelper('HtmlSelect')->getSelect('forwarder_id',$this->forwarderlist,'forwarder_id','forwarder_name',(isset($this->Request['forwarder_id'])?$this->Request['forwarder_id']:''),false,array('class'=>'inputfield','style'=>"width:60%"));?> 
				</div>
				<?php } ?>
				<div class="col-sm-3 col_paddingtop">
					<input type="submit" class="btn btn-danger btn-round" name="search" id="search" value="Search">
				</div>
			</form>	
				<div class="clear-all"></div>
				<div class="col-sm-12 col_paddingtop"></div>
           </div>	
	<!-- end filter -->
	<form method="post" action="" id="print_label" name="print_label">
	   <div class="col-sm-3 col_paddingtop">
		<select name="shipment_mode" id="shipment_mode"  class="inputfield" onchange="javascript:if(this.value == 'Delete' &amp;&amp; confirm('Selected shipment will be deleted\nAre you sure?') || this.value == 'PrintShippingList' || this.value == 'PerformaInvoice' || (this.value == 'PrintAll')) $('#print_label').submit(); else if(this.value == 'PrintAll' &amp;&amp; label_option == 'a4') jQuery('#dialog').dialog('open'); else return false;">
				  <option value=""><?php echo $this->translate("With Selected");?></option>
				  <option value="Delete"><?php echo $this->translate("Delete");?></option>
				  <option value="PrintAll"><?php echo $this->translate("Print All Label");?></option>
				  <option value="PrintShippingList"><?php echo $this->translate("Print Shipping List");?></option>
				  <option value="PerformaInvoice"><?php echo $this->translate("Performa Invoice");?></option>
				</select> </div>
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Shipping List");?></label>
				<select name="BulkShipping" id="BulkShipping" class="inputfield" style="width:60%" onchange="javascript:if(this.value != '') this.form.submit(); else return false; ">
				  <option value=""><?php echo $this->translate("Print Option");?></option>
				  <option value="1000">---0 To 1000---</option>
				  <option value="2000">---0 To 2000---</option>
				  <option value="3000">---0 To 3000---</option>
				</select> 
				</div>
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Print Label");?></label>
				<select name="BulkPrint" id="BulkPrint" class="inputfield" style="width:60%" onchange="javascript:if(this.value != '') this.form.submit(); else return false; ">
				  <option value=""><?php echo $this->translate("Selected Option");?></option>
				  <option value="1000">---0 To 1000---</option>
				  <option value="2000">---0 To 2000---</option>
				  <option value="3000">---0 To 3000---</option>
				</select> 
				</div>
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row">
					<span class="cell"><input type="checkbox" id="check_uncheck_all" onchange="check_uncheckALL(this)"></span>
					<span class="cell"><?php echo $this->translate("Receiver");?></span> 
					<span class="cell"><?php echo $this->translate("Reference");?></span> 
					<span class="cell"><?php echo $this->translate("Country");?></span> 
					<span class="cell"><?php echo $this->translate("Postalcode");?></span> 
					<span class="cell"><?php echo $this->translate("Forwarder");?></span> 
					<span class="cell"><?php echo $this->translate("Weight");?>(KG)</span>
					<span class="cell"><?php echo $this->translate("Quantity");?></span> 
					<span class="cell"><?php echo $this->translate("Service");?></span> 
					<span class="cell"><?php echo $this->translate("Sub-Service");?></span>
					<span class="cell"><?php echo $this->translate("Create Date");?></span>
					<span class="cell"><?php echo $this->translate("Pickup");?></span>					
					</div>
					<?php if($this->records['Total']>0){
					
						foreach($this->records['Records'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" <?php echo ($data['label_date']!='0000-00-00 00:00:00')?'style="background-color:green"':''?>><input type="checkbox" name="shipment_id[]"  id="shipment_id_<?= $data[SHIPMENT_ID]?>"  value="<?= $data[SHIPMENT_ID]?>" class="check_uncheck_class"></span>
							<span class="cell" data-label="Receiver"><?= $data[RECEIVER]?></span> 
							<span class="cell" data-label="Reference"><?= $data[REFERENCE]?></span>
							<span class="cell" data-label="Country"><?= $data['country_name']?></span>
							<span class="cell" data-label="Postalcode"><?= $data[ZIPCODE]?></span>
							<span class="cell" data-label="Forwarder"><?= $data['forwarder_name']?></span>
							<span class="cell" data-label="Weight"><?= $data[WEIGHT]?></span>
							<span class="cell" data-label="Quantity"><?= $data[QUANTITY]?></span>
							<span class="cell" data-label="Service"><?= $data['service_name']?></span>
							<span class="cell" data-label="Sub-Service"></span>
							<span class="cell" data-label="Create Date"><?= $data['create_date']?></span>
							<?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11 || $this->ModelObj->Useconfig['level_id']==4 || $this->ModelObj->Useconfig['level_id']==6){?>
							 <span class="cell" data-label="Pickup"><a href="javascript:void(0);" onclick="openbox('<?php echo $this->url(array('controller'=>'Planner','action'=>'directassign'),'default',true).$data['shipment_id'];?>','','')"><?=commonfunction::PickupSatus($data['assigned_date'],$data['pickup_status'])?></a></span>
							<?php }else{ ?>
							 <span class="cell" data-label="Pickup"><?=commonfunction::PickupSatus($data['assigned_date'],$data['pickup_status'])?></span>
							<?php } ?>
							<span class="cell" data-label="Action">
							 <a href="javascript:void(0)" onclick="window.top.location.href ='<?=$this->url(array('controller'=>'Shipment','action'=>'editshipment'),'default',  true).'?shipment_id='.Zend_Encript_Encription::encode($data['shipment_id'])?>';parent.jQuery.fancybox.close();"><img src="<?=IMAGE_LINK.'/edit-icon.png'?>" title="<?php echo $this->translate("Edit Shipment");?>" /></a>&nbsp;|&nbsp;
							 <img src="<?=IMAGE_LINK.'/print.png'?>" title="<?php echo $this->translate("Print");?>" onclick="printDelete('PrintAll','<?= $data[SHIPMENT_ID]?>')" />&nbsp;|&nbsp;
							 <img src="<?=IMAGE_LINK.'/delete.png'?>" title="<?php echo $this->translate("Delete Shipment");?>"  onclick="if(confirm('Selected shipment will be deleted\nAre you sure?')){printDelete('Delete','<?= $data[SHIPMENT_ID]?>')}"/>
							</span> 
						</div>
					<?php }}else{?>
						
						<div class="row odd">
							<b><?=$this->translate("Recod not found !");?></b> 
						</div>
					<?php }?>	
				</div>
				<div class="unit control">
                      <div class="nav-btns pull-right"> <?php echo commonfunction::PageCounter($this->records['Total'],$this->Request)?>
                      </div>
                    </div>
			</div></form></div></div>
		