  <div class="col-md-12" style="padding-top: 0px;">
  			<?php echo $this->getHelper('Messages')->getMessages();?> 
</div>
<?php //global $objSession; ?> 
      <h2 class="text-center form-title2">Enter your email address to reset your password.</h2>
      <div class="account-wall" style="width: 60%;margin: 5% auto 0px auto;">
  
	    <div class="col-sm-5 col-xs-12" style="padding-top: 20px;">
          <form class="form-login fs-form" action="" method="post" enctype="multipart/form-data">
            <label><i class="fa fa-envelope"></i></label>
			<input type="email" name="email" class="inputfield" style="width:89%;" id="email" required placeholder="Enter Email" autocomplete="off" value="" tooltipText="Type in your Email in this box" />
			 <div style="color: white;margin-bottom: 10px;margin-top: 10px;font-size: 14px;background: green;">
			<div class="Remember">
              <?php
			  //echo $objSession->infoMsg; 
			  //unset($objSession->infoMsg);
			  ?></div></div>          
              <button type="submit" class="loginbtn" value="resetpassword" name="submit">Reset Password</button>
           </form>
        
        </div>
	  </div>
	  <div class="clear-all"></div>
	  <div class="footer">&copy; 2016 ParcelPakket Website. All rights reserved. </div>