<?php global $objSession; ?>     
      <h1 class="text-center form-title">Welcome to Administration Control Panel</h1>
      <h2 class="text-center form-title2">Use a valid username and password to gain access to the administration console.</h2>
      <div class="account-wall">
  
	    <div class="col-sm-5 col-xs-12">
          <form class="form-login fs-form" action="" method="post" enctype="multipart/form-data">
            <label><i class="fa fa-user"></i></label>
			
			<input type="text" name="admin_userid" id="admin_userid" required placeholder="Username" autocomplete="off" value="<?=isset($_COOKIE['admin_userid']) ? $_COOKIE['admin_userid'] :''?>" tooltipText="Type in your username in this box" />
            <label><i class="fa fa-lock"></i></label>
             <input type="password"  name="admin_password" required id="admin_password" placeholder="Password" autocomplete="off" value="<?=isset($_COOKIE['admin_password']) ? $_COOKIE['admin_password'] : ''?>" tooltipText="Type in your password in this box" />
			 
			<div class="checkrem" style="color: red;font-size: 12px;">
			   <div class="col-sm-12 col-xs-12 Remember">
						  <?php
				 echo $objSession->errorMsg; 
				 unset($objSession->errorMsg);
				 ?></div></div>
            <div class="checkrem">
			<div class="col-sm-6 col-xs-12 Remember">
              <input type="checkbox"> Remember me</div>
			  <div class="col-sm-6 col-xs-12 forgot">
              <i class="fa fa-envelope"></i> <a href="lostpassword.html">Forgot password?</a>
			  </div></div>
			
          
              <button type="submit" class="loginbtn" name="submit">Login</button>
           </form>
        
        </div>
		
		
		 <form class="form-login fs-form" action="/Adminlogin/fronttracking" method="post" name="trackingparcel" enctype="multipart/form-data">
		<div class="col-sm-2 col-xs-12 col_nomargin"><div class="ybor">&nbsp;</div></div>
        <div class="col-sm-5 col-xs-12 col_nomargin">
		<div class="tracebox">
		<label><i class="fa fa-map-marker"></i></label>
          <input type="text" placeholder="Enter Parcel Number" required  name ="barcode"  value=""/>
		  			 <div style="color: red;font-size: 12px;background-color: white;margin-bottom: 10px;">
			<div class="Remember">
              <?php
			  echo $objSession->infoMsg; 
			  unset($objSession->infoMsg);
			  ?></div></div>
           <button name="submit" value="Track Parcel" type="submit" class="loginbtn">Track Parcel</button>
		   <div class="clearfix"></div>
        </div>
		
      </div>
	 </form>
	  </div>
	  <div class="clear-all"></div>
	  <div class="footer">&copy; 2016 ParcelPakket Website. All rights reserved. </div>