<div class="row decor-default p-email">
<style type="text/css">
.map_pro_details ul{margin:0px; padding:0px;}
.map_pro_details ul li { width:100%; border-bottom:1px solid #cccccc; overflow:auto}
.map_pro_details ul li p{margin:0px; padding:0px; line-height:20px; font-size:9px}
.map_pro_details ul li div.imglft{float:left; width:16%; margin:1%; text-align:center}
.map_pro_details ul li div.txtleft{width:55%; float:left; text-align:left}
.map_pro_details ul li div.imgrgt{float:left; width:25%; margin:1%; text-align:center}

</style>
        <div class="col-lg-12 col-md-12 col-sm-12 b-email">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Driver Current Location");?></h6>
          </div>
          <div class="row" style="padding-bottom:0px">
		  <div class="col-sm-12 col_paddingtop">
		   <div class="popup_map" id="map_convas" style="height: 400px; position: relative; overflow: hidden;"></div></div>
		  <div class="clearfix"></div>
			<div class="clearfix"></div>
        </div>
      </form>
    </div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiqLmgnnMs-zB-zeZxgOe9NgqGDI4XvY8"></script>
	
<script type="text/javascript">
function initialize() {
     var myOptions = {
		zoomControl:true,
	    zoomControlOptions: {
			style:google.maps.ZoomControlStyle.DEFAULT
	  	},
		zoom: 8,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	  }
	
	var map = new google.maps.Map(document.getElementById("map_convas"), myOptions);
	
	var latitude = '<?php echo implode('#',$this->driverlocation['Lat'])?>';
	var langitude = '<?php echo implode('#',$this->driverlocation['Lng'])?>';
	var addresses = '<?php echo implode('#',$this->driverlocation['Status'])?>';
	var location_icon = '<?php echo implode('#',$this->driverlocation['Icons'])?>';
	latitude = latitude.split('#');
	langitude = langitude.split('#');
	addresses = addresses.split('#');
	location_icon = location_icon.split('#');
    var infowindow = new google.maps.InfoWindow();

    var marker, i;
	var bounds = new google.maps.LatLngBounds();
    for (i = 0; i < latitude.length; i++) { 
      var newlatlang1 = new google.maps.LatLng(latitude[i],langitude[i]);
	  bounds.extend(newlatlang1);
	  map.fitBounds(bounds);	
	  map.setCenter(bounds.getCenter());
	  //flightPlanCoordinates.push(newlatlang1);
	  marker = new google.maps.Marker({	
					title: addresses[i],
					map: map, 
					position: newlatlang1,
					icon: location_icon[i]
	   });
      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(addresses[i]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  }
initialize();
</script>	
