<div class="row decor-default p-email">
<style type="text/css">
.map_pro_details ul{margin:0px; padding:0px;}
.map_pro_details ul li { width:100%; border-bottom:1px solid #cccccc; overflow:auto}
.map_pro_details ul li p{margin:0px; padding:0px; line-height:20px; font-size:9px}
.map_pro_details ul li div.imglft{float:left; width:16%; margin:1%; text-align:center}
.map_pro_details ul li div.txtleft{width:55%; float:left; text-align:left}
.map_pro_details ul li div.imgrgt{float:left; width:25%; margin:1%; text-align:center}

</style>
        <div class="col-lg-12 col-md-12 col-sm-12 b-email">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Driver Location");?></h6>
          </div>
          <div class="row" style="padding-bottom:0px">
		  <div class="col-sm-12 col_paddingtop">
		   <div class="popup_map" id="map_convas" style="height: 400px; position: relative; overflow: hidden;"></div></div>
		  <div class="clearfix"></div>
			<div class="clearfix"></div>
        </div>
      </form>
    </div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiqLmgnnMs-zB-zeZxgOe9NgqGDI4XvY8"></script>
	
<script type="text/javascript">

 	geocoder = new google.maps.Geocoder();

	var geocoder, map;
	var addressdata =[]; var statusdata =[];	var addresslatlang=[];
	
	var data ='<?php echo $this->driverlocation['Time']?>';
	var datastatus ='<?php echo $this->driverlocation['Time']?>';
	var datalatlang = '<?php echo $this->driverlocation['Location']?>';
	var myOptions = {
		zoom: 8,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	  }
	
	map = new google.maps.Map(document.getElementById("map_convas"), myOptions);
	
	codeAddress();

function codeAddress() {
	var deliveryStatus = '1'; 
	var ErrorStatus = '0'; 
	
	var city =[];	
	var flightPlanCoordinates = []; 
	var addressStatus = [];
	var j=0; 
	
	addressdata = data.split("#"); 
	statusdata  = datastatus.split("#");
	addresslatlang 	= datalatlang.split("#");
	
	var bounds = new google.maps.LatLngBounds();
	
	for(var i=0;i<addressdata.length;i++){
			
		var address = addressdata[i];	
		var addstatus =  statusdata[i];
		var newlatlang = addresslatlang[i];
		var newdata = newlatlang.split(",");
		
		city.push(address);  
		addressStatus.push(addstatus);
			var newlatlang1 = new google.maps.LatLng(newdata[0],newdata[1]);	
				bounds.extend(newlatlang1);
				map.fitBounds(bounds);
				
				map.setCenter(bounds.getCenter());
			
				flightPlanCoordinates.push(newlatlang1); // use to drow line on map
			
				var cityname = city[j]; 
				var contentString=addressStatus[j]; 
				
				j= j + 1;
				var imagepath = '<?php print_r(IMAGE_LINK) ?>';
				var totalstatus = addstatus.split(","); 
				var totalstatus = totalstatus.length;
				if(((addressdata.length)-1)==i){
				    var iconpath =imagepath+'/pickup.png';	
				 }else{
				    var iconpath =imagepath+'/driver_locations.png';
				 }
				//set marker images
				
				// set marker 
				var marker = new google.maps.Marker({	
					title: cityname,
					map: map, 
					position: newlatlang1,
					icon: iconpath 
	
				});
				
				// set popup data (show when click on marker)
				var infoWindow = new google.maps.InfoWindow(), marker, i;
			
				// show information, on marker click
				google.maps.event.addListener(marker, 'click', (function(marker, i) {
					return function() {
						infoWindow.setContent(addressStatus[i]);
						infoWindow.open(map, marker);
					}
				})(marker, i));

			// add polyline between markers
			var flightPath = new google.maps.Polyline({
				
				path: flightPlanCoordinates,
				geodesic: true,
				strokeColor: '#008000',
				strokeOpacity: 0.8,
				strokeWeight: 1
			});
			
			flightPath.setMap(map);
		}
	}
	
</script>	
