
	
<?php 
echo $this->headScript()
->prependFile($this->basePath(). '/js/lumino.glyphs.js')
->prependFile($this->basePath(). '/js/bootstrap-datepicker.js')
->prependFile($this->basePath(). '/js/easypiechart-data.js')
->prependFile($this->basePath(). '/js/easypiechart.js')
->prependFile($this->basePath(). '/js/chart-data.js')
->prependFile($this->basePath(). '/js/chart.min.js')
->prependFile($this->basePath(). '/js/bootstrap.min.js')
->prependFile($this->basePath(). '/js/jquery-1.11.1.min.js')
 ; ?>
	 
	<script>
		!function ($) {
			$(document).on("click","ul.nav li.parent > a > span.icon", function(){		  
				$(this).find('em:first').toggleClass("glyphicon-minus");	  
			}); 
			$(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
		}(window.jQuery);

		$(window).on('resize', function () {
		  if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
		})
		$(window).on('resize', function () {
		  if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
		})
	</script>