
<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="filter_form" name="filter_form">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-3 col_paddingx10">
				<input type="text" name="search_word" id="search_word" value="<?php echo isset($this->Request['search_word'])?$this->Request['search_word']:''?>" class="inputfield">
				</div>
				<div class="col-sm-2 col_paddingx10">
				<input type="submit" name="submit" value="Search" class="btn btn-danger btn-round">
				</div>
				<div class="col-sm-12 col_paddingtop"></div>
				</div>
		</div>
		<!-- end filter -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><?php echo $this->translate("Invoice Number");?></span> 
					<span class="cell"><?php echo $this->translate("Invoice Amount");?></span> 
					<span class="cell"><?php echo $this->translate("Invoice Date");?></span> 
					<span class="cell"><?php echo $this->translate("Paid Amount");?></span> 
					<span class="cell"><?php echo $this->translate("Balance");?></span> 
					<span class="cell"><?php echo $this->translate("Payment Mode");?></span>
					<span class="cell"><?php echo $this->translate("Payment Date");?></span>
					<span class="cell"><?php echo $this->translate("Action");?></span>				
					</div>
					<?php if($this->invoiceList['Total']>0){
						foreach($this->invoiceList['Record'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
						<span class="cell" data-label="Invoice"><?=$data['invoice_number'];?></span>
							<span class="cell" data-label="Invoice Amount"><?= "&euro; ".commonfunction::numberformat($data['total_amount'])?></span>
							<span class="cell" data-label="Invoice Date"><?= $data['invoice_date']?></span>
							<span class="cell" data-label="Paid">
							<?php echo ($data['payment_status']==0)?'Not Paid':"&euro; ".commonfunction::numberformat($data['paid_amount']);?> &nbsp;</span>
							<span class="cell" data-label="Balance"><?=commonfunction::numberformat($data['total_amount']-$data['paid_amount'])?></span>
							<span class="cell" data-label="Payment Mode"><?php echo ($data['payment_status']=='0')?'Not Paid':$data['payment_mode'];?></span>
							<span class="cell" data-label="Payment Date"><?=($data['payment_status']==0)?'Not Paid':date('F- d Y',strtotime($data['payment_date']))?></span>
							<span class="cell" data-label="Action">
							 <a href="javascript:void(0);"  onclick="openbox('<?php echo INVOICE_OPEN.date('Y',strtotime($data['invoice_date'])).'/'.date('M',strtotime($data['invoice_date'])).'/'.$data['file_name'];?>','90%','80%')"><img src="<?=IMAGE_LINK.'/print.png'?>" title="Print Invoice"></a>
							 
							</span> 
						</div>
					<?php }}else{?>
						
						<div class="row odd">
							<span class="cell" colspan="6"><b><?=$this->translate("Recod not found !");?></b></span> 
						</div>
					<?php }?>	

				</div>
					 	
			</form>	
			</div></div></div>
<script>
function Addrouting(){
   var user_id = $('#user_id').val();
   if(user_id>0){
       openbox('<?php echo $this->url(array('controller'=>'Routing','action'=>'addrouting'),'default',true);?>?user_id='+user_id,'70%','90%');
   }else{
     alert('Please select Depot first');return false;
   }
}
function Editrouting(url){
    openbox(url,'70%','90%');
}
</script>			