	<script src="<?php echo $this->baseUrl('public/js/account.js');?>"></script>
	
	<div id="table"><div class="header-row row">
		<span class="cell" style="text-align:center"><h6><?php echo $this->translate("Customer Sender Address");?></h6></span> 
	</div></div>
	
	<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
        <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <ul class="nav nav-tabs nav-justified">
                <li> <a href="senderaddress?token=<?php echo $this->token;?>"><?php echo $this->translate("List ")?><i class="fa fa-folder"></i></a> </li>
                	<?php if($this->addressaction=='Add'){?>
						<li  class="active"> <a href="senderaddressform?token=<?php echo $this->token;?>"><?php echo $this->translate("Add Sender Address ")?><i class="fa fa-ticket"></i></a> </li>
					<?php }else{ ?>	
						<li  class="active"> <a href="senderaddressform?token=<?php echo $this->token;?>&address=<?php echo $this->address;?>"><?php echo $this->translate("Update Sender Address ")?><i class="fa fa-ticket"></i></a> </li>
					<?php }?>	
				
              </ul>
			</div>
		</div>	
	</div>	
	
		
	<div class="col-md-2"></div>
		<div class="col-md-8" >
			<div style="text-align:center;color:#FF0000"><?php echo $this->translate("* Marked fields are mandatory");?></div>
			<div id="table"><div class="header-row row">
				<?php if($this->addressaction=='Edit'){ ?>
					<span class="cell" style="text-align:center"><?php echo $this->translate("Update Sender Address");?></span> 
				<?php }else{ ?>
				<span class="cell" style="text-align:center"><?php echo $this->translate("Add New Sender Address");?></span> 
				<?php }?>
			</div></div>
			
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1" style="background-color:white;">
					<?php echo $this->senderaddress; ?>
				</div>
			</div>
		</div>
	<div class="col-md-2"></div>
	
	<script>
		$(document).ready(function() {
			var mode = '<?php echo $this->addressaction; ?>';
			var logoimage = '<?php echo $this->senderLogo;?>';	
			if((mode=='Edit')){
				$('#imagefile').hide();
			}
			if(logoimage==''){
				$('#imagefile').show();
			}
			
		});	
	</script>