<script src="<?php echo $this->baseUrl('/public/js/planner.js')?>"></script> 

<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-1">
					<form action="" method="post" name="assigned_form" id="assigned_form">
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Assigned Pickup')?></div>
					  <div class="clear-all"></div>
					   <div class="col-sm-4 col_paddingtop">
						 <label><?php echo $this->translate("Filter Driver"); ?></label>
							<?php echo $this->getHelper('HtmlSelect')->getSelect('filterdriver_id',$this->driverList,'driver_id','driver_name',(isset($this->Request['filterdriver_id'])?$this->Request['filterdriver_id']:''),false,array('class'=>'inputfield','onchange'=>'if(this.value!=""){this.form.submit()}')); ?>
						</div>
					  <div class="col-sm-4 col_paddingtop">
						 <label><?php echo $this->translate("Customer"); ?></label>
							<?php echo $this->getHelper('HtmlSelect')->getSelect('user_id',$this->customerList,'user_id','company_name',(isset($this->Request['user_id'])?$this->Request['user_id']:''),true,array('class'=>'inputfield','onchange'=>'if(this.value!=""){this.form.submit()}')); ?>
						</div>
						 <div class="col-sm-4 col_paddingtop">
						 <label><?php echo $this->translate("Re-assign Driver"); ?></label>
							<?php echo $this->getHelper('HtmlSelect')->getSelect('driver_id',$this->driverList,'driver_id','driver_name','',false,array('class'=>'inputfield','onchange'=>'if(this.value!=""){bulkreAssign(this.value)}')); ?>
						</div>
						
						 <div class="col-sm-2 col_paddingx10">
						<input type="button" name="driverManifest" id="driverManifest" onclick="PrintDriverManifest()" value="Driver Manifest" class="btn btn-danger btn-round">
					  </div>
					
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="datatableid">
					    <thead>
						<tr>
								<th><input type="checkbox" name="check_uncheck_all" id="check_uncheck_all" onchange="check_uncheckALL(this)"></th>
								<th><?=$this->translate('Customer Name');?></th>
								<th><?=$this->translate('Total Weight');?> </th>
								<th><?=$this->translate('Total Quantity');?></th>
								<th><?=$this->translate('Pickup Address');?></th>
								<th><?=$this->translate('Pickup Time');?></th>
								<th><?=$this->translate('Pickup Date');?></th>
								<th><?=$this->translate('Driver');?></th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->schedulepickup)>0){
						 foreach($this->schedulepickup as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; 
						  $pickupurl = '?pickup_detail='.urlencode(commonfunction::Compress($data['parcel_type'].'$'.$data['barcode_id'].'$'.$data['name'].'^'.$data['street1'].'^'.$data['street2'].'^'.$data['zipcode'].'^'.$data['city'].'^'.$data['country'].'$'.$data['pickup_date'].'$'.$data['pickup_time'].'$'.$data['user_id'].'$'.$data['history_id']));
						  $reassignurl = 'pickup_detail='.$data['parcel_type'].'$'.$data['barcode_id'].'$'.$data['user_id'].'$'.$data['history_id'];
						  $manifestdata = $data['parcel_type'].'$'.$data['barcode_id'].'$'.$data['name'].'^'.$data['street1'].'^'.$data['street2'].'^'.$data['zipcode'].'^'.$data['city'].'^'.$data['country'].'$'.$data['pickup_date'].'$'.$data['pickup_time'].'$'.$data['user_id'].'$'.$data['total_weight'].'$'.$data['total_quantity'];
						 $background = '';
						 if($data['manual_pickup_id']>0){
						     $background = 'style="background-color:tomato"';
						 }else{
						    switch($data['parcel_type']){
						      case 2:
							      $background = 'style="background-color:cadetblue"';
							  break;
							  case 3:
							     $background = 'style="background-color:bisque"';
							  break;
							  case 5:
							     $background = 'style="background-color:#8bc34a"';
							  break;
						   }
						 }
						?>
						<tr class="<?php echo $class;?>" <?php echo $background;?>>
						<td width="4%"><input type="checkbox" name="barcode_id[]" id="barcode_id_<?php echo $key;?>" value="<?php echo $manifestdata;?>" class="check_uncheck_class"></td>
                        <td width="10%" data-label="Customer"><?php echo $data['company_name']; ?></td> 
						<td width="7%" data-label="Weight"><?php echo $data['total_weight']; ?></td>
						<td width="5%" data-label="Quantity"><?php echo $data['total_quantity']; ?></td> 
						<td width="7%" data-label="Pickup Address"><?php echo $data['name'].'<br>'.$data['street1'].'<br>'.$data['street2'].'<br>'.$data['zipcode'].' '.$data['city'].'<br>'.$data['country']; ?></td> 
						<td width="5%" data-label="Pickup Time"><a href="javascript:void(0)" onclick="openbox('<?php echo $this->url(array('controller'=>'Planner','action'=>'manualpickup'),'default',true).$pickupurl?>','60%','70%')"><?php echo $data['pickup_time']; ?></a></td>
						<td width="10%" data-label="Pickup Date"><a href="javascript:void(0)" onclick="openbox('<?php echo $this->url(array('controller'=>'Planner','action'=>'manualpickup'),'default',true).$pickupurl?>','60%','70%')"><?php echo $data['pickup_date']; ?></a></td>
						<td width="5%" data-label="Quantity"><?php echo $data['driver_name']; ?></td> 
						<td width="5%" data-label="Action">
						<a href="javascript:void(0);" onclick="$('#driver_span<?php echo $key;?>').toggle()" title="Re-assign"> <i class="fa fa-edit fa-2x" title="Re-assign"></i></a>
						<span id="driver_span<?php echo $key;?>" style="display:none"><?php echo $this->getHelper('HtmlSelect')->getSelect('driver_id',$this->driverList,'driver_id','driver_name',$data['driver_id'],false,array('class'=>'inputfield','onchange'=>'if(this.value!=""){reAssign("'.$reassignurl.'",this.value)}')); ?></span>
					   </td> 
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td></td><td></td><td></td><td></td><td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td><td></td><td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 $('#datatableid').DataTable( {
		"pageLength": 100,
		"lengthMenu": [[10, 25, 50, 100, 200, 500, -1], [10, 25, 50, 100, 200, 500, "All"]],
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
 						column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>