<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/timepicker/jquery.ui.timepicker.css')?>">
<script src="<?php echo $this->baseUrl('/public/timepicker/include/ui-1.10.0/jquery.ui.widget.min.js')?>"></script>
<script src="<?php echo $this->baseUrl('/public/timepicker/jquery.ui.timepicker.js')?>"></script>
<form action="" method="post" name="manual_pickup" class="inputbox" >
<input type="hidden" name="parcel_type" id="parcel_type" value="<?php echo isset($this->pickup_date[0])?$this->pickup_date[0]:''?>">
<input type="hidden" name="barcode_id" id="barcode_id" value="<?php echo isset($this->pickup_date[1])?$this->pickup_date[1]:''?>">
<input type="hidden" name="user_id" id="user_id" value="<?php echo isset($this->pickup_date[5])?$this->pickup_date[5]:''?>">
<input type="hidden" name="history_id" id="history_id" value="<?php echo isset($this->pickup_date[6])?$this->pickup_date[6]:''?>">
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Manual Pickup");?></h6>
          </div>
          <div class="row">
		  <div class="col-sm-5 col_paddingtop">
			 <label><?php echo $this->translate("Pickup Date"); ?></label>
				 <input type="text" name="pickup_date" id="pickup_date" class="inputfield" value="<?php echo isset($this->pickup_date[3])?$this->pickup_date[3]:''?>">
            </div>
   <div class="col-sm-3 col_paddingtop">
			 <label><?php echo $this->translate("Pickup Time"); ?></label>
				 <input type="text" name="pickup_time" id="pickup_time" class="inputfield" value="<?php echo isset($this->pickup_date[4])?$this->pickup_date[4]:''?>">
            </div>
			<?php $Address = commonfunction::explode_string($this->pickup_date[2],'^');?>
   <div class="clearfix"></div>
            <div class="col-sm-5 col_paddingtop">
			 <label><?php echo $this->translate("Name"); ?></label>
				 <input type="text" name="name" id="name" class="inputfield" value="<?php echo isset($Address[0])?$Address[0]:''?>">
            </div>
   <div class="col-sm-4 col_paddingtop">
			 <label><?php echo $this->translate("Street1"); ?></label>
				 <input type="text" name="street1" id="street1" class="inputfield" value="<?php echo isset($Address[1])?$Address[1]:''?>">
            </div>
	 <div class="col-sm-3 col_paddingtop">
	 <label><?php echo $this->translate("Street2"); ?></label>
		 <input type="text" name="street2" id="street2" class="inputfield" value="<?php echo isset($Address[2])?$Address[2]:''?>">
	</div>
   <div class="clearfix"></div>
   <div class="col-sm-3 col_paddingtop">
			 <label><?php echo $this->translate("Zipcode"); ?></label>
				 <input type="text" name="zipcode" id="zipcode" class="inputfield" value="<?php echo isset($Address[3])?$Address[3]:''?>">
            </div>
   <div class="col-sm-5 col_paddingtop">
			 <label><?php   echo $this->translate("City"); ?></label>
				<input type="text" name="city" id="city" class="inputfield" value="<?php echo isset($Address[4])?$Address[4]:''?>">
            </div>
  
   <div class="col-sm-4 col_paddingtop">
			 <label><?php echo $this->translate("Country"); ?></label>
				 <input type="text" name="country" id="country" class="inputfield" value="<?php echo isset($Address[5])?$Address[5]:''?>">
            </div>
   <div class="clearfix"></div>
   <div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
	  <div class="col-sm-2 col_paddingtop"> <input type="submit" name="manualpickup" value="Manual Pickup" class="btn btn-danger btn-round"></div>
   </div>
</div>
</div>
</form>
<script type="text/javascript">	
	$(function() {
		$( "#pickup_date" ).datepicker({
		  dateFormat: 'yy-mm-dd',
		  showOtherMonths: true,
		  selectOtherMonths: true
		});
	});
	$('#pickup_time').timepicker();
</script>	