<div class="content container-fluid">
    <div class="input-title"><?php echo $this->translate('Add New Contact Address') ?></div>
</div>

<form id="contactaddress" name="contactaddress" class="inputbox" method="post">
    <div class="col-sm-3 col_paddingtop"></div>
    <div class="col-sm-6 col_paddingtop">
        <div class="row">
			<div class="col-sm-12 col_paddingtop">
		       <label for="customer_number" class="required"><?php echo $this->translate('Customer Number:') ?></label>
			   <input type="text" name="customer_number" value="" class="inputfield">
			</div>
			<div class="col-sm-6 col_paddingtop">
		       <span style="color:red;">*</span><label for="name" class="required"><?php echo $this->translate('Name:') ?></label>
			   <input type="text" name="name" value="" class="inputfield" required>
			</div>
			<div class="col-sm-6 col_paddingtop">
		       <label for="contact" class="required"><?php echo $this->translate('Contact:') ?></label>
			   <input type="text" name="contact" value="" class="inputfield">
			</div>
			
			<div class="col-sm-4 col_paddingtop">
		       <span style="color:red;">*</span><label for="street" class="required"><?php echo $this->translate('Street:') ?></label>
			   <input type="text" name="street" value="" class="inputfield" required>
			</div>
			
			<div class="col-sm-4 col_paddingtop">
		       <span style="color:red;">*</span><label for="street_no" class="required"><?php echo $this->translate('Number:') ?></label>
			   <input type="text" name="street_no" value="" class="inputfield" required>
			</div>
			
			<div class="col-sm-4 col_paddingtop">
		       <span style="color:red;">*</span><label for="address" class="required"><?php echo $this->translate('Address:') ?></label>
			   <input type="text" name="address" value="" class="inputfield" required>
			</div>
            
			<div class="col-sm-12 col_paddingtop">
		       <span style="color:red;">*</span><label for="street2" class="required"><?php echo $this->translate('Street 2:') ?></label>
			   <input type="text" name="street2" value="" class="inputfield" required>
			</div>
			
			<div class="col-sm-12 col_paddingtop">
		       <span style="color:red;">*</span><label for="postal_code" class="required"><?php echo $this->translate('Zip Code:') ?></label>
			   <input type="text" name="postal_code" value="" class="inputfield" required>
			</div>
			
			<div class="col-sm-12 col_paddingtop">
		       <span style="color:red;">*</span><label for="city" class="required"><?php echo $this->translate('City:') ?></label>
			   <input type="text" name="city" value="" class="inputfield" required>
			</div>
			
			<div class="col-sm-12 col_paddingtop">
		        <span style="color:red;">*</span><label for="country" class="required"><?php echo $this->translate('Country:') ?></label></br>
			    <?=$this->getHelper('HtmlSelect')->getSelect('country',$this->countries,'country_id','country_name','',false,array('class'=>'inputfield','style'=>'width:60%','required'=>'required')); ?>
			</div>
			
			<div class="col-sm-12 col_paddingtop">
		       <label for="phone" class="required"><?php echo $this->translate('Phone:') ?></label>
			   <input type="text" name="phone" value="" class="inputfield">
			</div>
			
			<div class="col-sm-12 col_paddingtop">
		       <label for="email_address" class="required"><?php echo $this->translate('Email Address:') ?></label>
			   <input type="text" name="email_address" value="" class="inputfield">
			</div>
			
            <div class="col-sm-12 col_paddingtop">
               <input type="submit" name="submit" value="Save Profile" class="btn btn-danger btn-round">
			</div>
		</div>
	</div>
</form>
