
<span class="cell" data-label="Country"><?php  echo $this->definition; ?></span>

									<span class="cell" data-label="Min Weight"><?php  echo $this->ledger_id; ?></span>

									<span class="cell" data-label="Max weight"><?php  echo $this->btw; ?></span>
									<span class="cell" data-label="Max weight"><?php  echo $this->credit; ?></span>
								<span class="cell" data-label="Max weight" onclick="removerow($(this).parent('div').attr('rowid'))" >Remove</span>