		<div id="table">
			<div class="header-row row">
			<span class="cell" style="text-align:center"><?php echo $this->translate("Update Shop Setting ");?></span>
		</div></div>

	<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">
			
	<form method="post" action="" id="editshopform" name="editshopform">
		
		<div id="tablegrid">
			<table width="100%" border="0">
				<input type="hidden" name="addPos" id="addPos" value="<?= count($this->multishopUrls) ?>" />
				<tbody>
					<tr>
						<td width="20%">
							<label for="user"><b><?php echo $this->translate("Customer ");?></b></label>
						</td>
						<td width="30%">
							<label for="user" style="text-align:center"><?php echo $this->customerName;?></label>
						</td>
					
						<td width="15%">
							<label for="shoptype"><b><?php echo $this->translate("Webshop ");?></b></label>
						</td>
						
						<td width="40%">
							<select id="shoptype" name="shop_type_id" style="width:80%; padding:5px;15px">
								<option value="" ><?php echo " Select Webshop "?></option>
								<?php foreach($this->WebshopList as $key=>$webshop){ 
									$select = '';
									if($this->record['shop_type_id']==$key){
										$select ="selected='selected'"; 
									}
								?>
								 <option value="<?php echo $key; ?>" <?php echo $select; ?>><?php echo $webshop;?></option>
								<?php } ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td width="20%">
							<label for="shopname"><b><?php echo $this->translate("Shop Name ");?></b></label>
						</td>
						<td width="30%">
							<input type="text" name="shop_name" value="<?= $this->record['shop_name'] ?>" style="width:80%; padding:5px;15px">
						</td>
						
						<td width="15%">
							<label for="shopurl"><b><?php echo $this->translate("Shop URL ");?></b></label>
						</td>
						
						<td width="30%">
							<input type="text" name="shop_url" value="<?= $this->record['shop_url'] ?>" style="width:80%; padding:5px;15px">
						</td>
					</tr>
					
					<tr>
						<td width="20%">
							<label for="apikey"><b><?php echo $this->translate("API Key ");?></b></label>
						</td>
						<td width="30%">
							<input type="text" name="api_key" value="<?= $this->record['api_key'] ?>" style="width:80%; padding:5px;15px">
						</td>
						
						<td width="15%">
							<label for="apisecret"><b><?php echo $this->translate("API Secret ");?></b></label>
						</td>
						
						<td width="30%">
							<input type="text" name="api_secret" value="<?= $this->record['api_secret'] ?>" style="width:80%; padding:5px;15px">
						</td>
					</tr>
					
					<tr>
						<td width="20%">
							<label for="service"><b><?php echo $this->translate("Service ");?></b></label>
						</td>
						<td width="30%">
							<select id="service" name="service_id" style="width:80%; padding:5px;15px" onchange="$.getaddservice(this.value);">
								<option value="" ><?php echo " Select Service "?></option>
								<?php foreach($this->ServiceList as $key=>$service){ 
									$select = '';
									if($this->record['service_id']==$key){
										$select ="selected='selected'"; 
									}
								?>
								 <option value="<?php echo $key; ?>" <?php echo $select; ?>><?php echo $service;?></option>
								<?php } ?>
							</select>
						</td>
						
						<td width="20%">
							<label for="addservice"><b><?php echo $this->translate("Additional Service ");?></b></label>
						</td>
						
						<td width="30%">
							<select id="addservice" name="add_service_id" style="width:80%; padding:5px;15px">
								<option value="" ><?php echo " ---Additional Service--- "?></option>
								
							</select>
						</td>
					</tr>
					
					<tr>
						<td width="20%">
							<label for="weight"><b><?php echo $this->translate("Weight ");?></b></label>
						</td>
						<td width="30%">
							<input type="text" name="weight" value="<?= $this->record['weight'] ?>" style="width:80%; padding:5px;15px">
						</td>
						
						<td width="20%">
							<label for="weight"><b><?php echo $this->translate("Add Multishop URL ");?></b></label>
						</td>
						<td>
							<label for="type"><input type="radio" name="multishop" id="type-0" value="0" <?= $this->Nflag ?> onclick="showhideRow(this.value); " /><?php echo $this->translate("NO");?></label>&nbsp;&nbsp;
							
							<label for="type"><input type="radio" name="multishop" id="type-1" value="1" <?= $this->Yflag ?> onclick="showhideRow(this.value); " /><?php echo $this->translate("YES");?></label>
						</td>
						
					</tr>
					
					<?php if(count($this->multishopUrls)>0){ 
						$i=1;
						foreach($this->multishopUrls as $multiurl) {?>
						<tr id="row_<?=$i; ?>">
							<td width="15%">
								<label for="multishopurl"><b><?php echo $this->translate("Multishop URL ");?></b></label>
							</td>
							
							<td width="30%">
								<input type="text" name="multiurl[]" value="<?= $multiurl['shop_url'] ?>" style="width:80%; padding:5px;15px">
							</td>
							<?php if($i==count($this->multishopUrls)){ ?>
								<td width="5%"><img src="<?php print IMAGE_LINK; ?>/addmore.gif" align="absmiddle" alt="addmore" title="Add More" border="0" class="addMore" onclick="$.addnewrow();" id="col_<?=$i ?>" /></td><td></td>
							<?php }else{ ?>
								<td><img src='<?php echo IMAGE_LINK; ?>/remove.png' align='absmiddle' alt='removerow' title='Remove' border='0' class='del' onclick ='$.removerow(<?=$i ?>);'  id='col_<?=$i ?>'/></td><td></td>	
							<?php } ?>
						</tr>
					<?php $i++; } }else{ ?>
						<tr id="row_1" style="display:none;">
							<td width="15%">
								<label for="multishopurl"><b><?php echo $this->translate("Multishop URL ");?></b></label>
							</td>
							
							<td width="30%">
								<input type="text" name="multiurl[]" style="width:80%; padding:5px;15px">
							</td>
							<td width="5%"><img src="<?php print IMAGE_LINK; ?>/addmore.gif" align="absmiddle" alt="addmore" title="Add More" border="0" class="addMore" onclick="$.addnewrow();" id="col_1" /></td><td></td>
						</tr>
					<?php } ?>	
				</tbody>
			
			</table>
		</div>	
			<div style="text-align:center">
				<input type="submit" name="editshop" id="editshop" value="Update" class="btn btn-danger btn-round">
			</div>
	</form></div></div>
	
<script type="text/javascript">
	
	$(document).ready(function() {
		var serviceId = '<?= $this->record['service_id']; ?>';
		if(serviceId>0){
			$.getaddservice(serviceId);
		}
	});
	
	
	$.getaddservice=function(service){
		
		var addservice = '<?= $this->record['add_service_id']; ?>';
		if(service>0){
			$.ajax({
				Type:"POST",
				url: '<?=$this->url(array('controller'=>'Shopapi','action'=>'getadditionalservice'),'default',true)?>',
				data: {service: service, addservice: addservice},
				success : function(msg){ //alert(msg);return false;
					$("#addservice").html(msg); 	
				}
			});
		}
	}
	
	function showhideRow(id){
		var totalrow = $("#addPos").val();	
		if(totalrow==0){
			$("#addPos").val(1);
			$('#row_1').show();
		}
		else{
			if(id==0){
				for(var i=1; i<=totalrow; i++){	
					$('#row_'+i).hide();
				}
			}
			else{
				for(var i=1; i<=totalrow; i++){	
					$('#row_'+i).show();
				}
			}
		}	
	}
	
	$.addnewrow = function(){
		 	
			var posVal = $("#addPos").val();
			var possVal = parseInt(posVal)+1;
			$("#addPos").val(possVal);
			
			
			var appendTxt = "<tr id='row_"+possVal+"'><td><label for='multishopurl'><b><?php echo $this->translate('Multishop URL ');?></b></label></td><td><input type='text' name='multiurl[]' style='width:80%; padding:5px;15px'></td><td><img src='<?php echo IMAGE_LINK; ?>/addmore.gif' align='absmiddle' alt='addmore' title='Add More' border='0' class='addMore' onclick ='$.addnewrow();'  id='col_"+possVal+"'/></td><td></td></tr>";
			
			$("tr:last").after(appendTxt);
			
			$('#col_'+posVal).attr('src','<?php echo IMAGE_LINK;?>/remove.png');
			$('#col_'+posVal).attr('class','del');
			$('#col_'+posVal).attr('title','Remove');
			$('#col_'+posVal).attr('alt','removerow');
			$('#col_'+posVal).attr('onclick','$.removerow('+posVal+')');
		}
		
	$.removerow = function(id){ //alert(id);return false;
		 	$('#row_'+id).remove();
			var nextrow = parseInt(id)+1;	
			var newrow = id;
			var totalrow = $("#addPos").val();	
			if(id<totalrow){
				for(var i=nextrow; i<=totalrow; i++){
						
					$('#row_'+i).attr('id','row_'+newrow);
					if(i!=totalrow){
						$('#col_'+i).attr('onclick','$.removerow('+newrow+')');
					}
					$('#col_'+i).attr('id','col_'+newrow);
					
					newrow = parseInt(newrow)+1;
				}
		 	}

			var possVal = parseInt(totalrow)-1;
			$("#addPos").val(possVal);
		 }
		 
</script>	