	<div class="row row-broken">
        <div class="col-sm-12">
			<div class="tabs" id="seventh-tabs">
			   
			  
				<div class="tab-content">
					 <div class="tab-pane fade in active" id="tab-1">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Accounting Btw Rates')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-2 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede">
						<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Accounting','action'=>'addeditbtwrates'),'default',true)?>?mode=add','60%','55%');"> <i class="fa fa-plus-square"></i><?php echo $this->translate('Add New Btw Rate')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('Rate Type');?></th>
								<th><?=$this->translate('Effective Date');?> </th>
								<th><?=$this->translate('BTW Rate');?></th>
								<th><?=$this->translate('Status');?></th>
								<th><?=$this->translate('Action');?></th>
								 
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->BtwRates)>0){
						 foreach($this->BtwRates as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
                         
						<td width="10%" data-label="Rate Type"><?=$data['rate_type']; ?></td>
						<td width="10%" data-label="Effective Date"><?=$data['effective_date']; ?></td> 
						<td width="10%" data-label="BTW Rate"><?=$data['btw_rate']; ?></td> 
						  
						 
						  
						<td width="10%">
							<span class="cell" data-label="Status" id="statusSpan_<?=$key?>" >
								<?php if($data['status'] == "1") {  ?>
									<img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=AccountingBtwRates?>','Status','0','btwrate_id','<?=$data['btwrate_id']?>','<?=$key?>');" title="Change Status into In-Active" class="changeStatus" />
									<?php } else { ?>
									<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=AccountingBtwRates?>','Status','1','btwrate_id','<?=$data['btwrate_id']?>','<?=$key?>');" title="Change Status into Active" class="changeStatus" />
									<?php } ?>
							</span></td>
						
						
						<td width="10%" data-label="Action">
						 		<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Accounting','action'=>'addeditbtwrates'),'default',true).'?mode=edit&id='.$data['btwrate_id']?>','60%','55%');"> 
						 			<i class="fa fa-edit fa-2x"></i>
								</a>
						
                        </td> 
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td><td></td><td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
				</div>
			</div>
        </div>
     </div>
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>