
<div class="col-sm-12 col_paddingx10"><span id="error_message" name="error_message" style="color: green;"></span></div><div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-7">
					<form method="post" name= "blockip_form">
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Text Translation')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-3 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede">
						<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Translation','action'=>'addtext'),'default',true).'?mode=add'?>','60%','80%');"> <img src="<?=IMAGE_LINK?>/addmore.gif" /> <?php echo $this->translate('Add New Text')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
					</div>
             
					 <div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('Translation for');?></th>
									<?php foreach($this->Language as $value) {?>
									<th><?=ucfirst($value['language_name']);?></th>
								<?php }?>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						//echo"<pre>";print_r($this->TranslationList); die;
						if(count($this->TranslationList)>0){
						 foreach($this->TranslationList as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
						<td data-label="Translation for"><?=$data['translationFor']?></td>
									<?php foreach($this->Language as $value) {?>
									<td data-label="<?=$value['language_name'];?>"><?=$data[$value['language_name']];?></td>
								<?php }?>
						<td data-label="Action">
						<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Translation','action'=>'addtext'),'default',true).'?mode=edit&token='.Zend_Encript_Encription:: encode($data['id'])?>','60%','85%');"> <i class="fa fa-edit fa-2x "></i></a>
                        </td> 
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td>
						  <td></td>
						  <td></td>
						  <td></td>
						  <td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>