	<div class="row row-broken">
        <div class="col-sm-12">
			<div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
				<?=$this->ModelObj->tabNavigation(); ?>
              </ul>
			  
				<div class="tab-content">
					<div class="tab-pane fade in active" id="tab-1">
						<div class="col-inside-lg decor-default">
             	  
							<div class="row tab-filter row_nopadding decor-success tab-position">
							 <div class="input-title"><?php echo $this->translate('Accounting Bank')?></div>
							  <div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
								  <div class="col-sm-2 col_paddingtop">
            					  </div>
								  <div class="col-sm-8 col_paddingtop">
								  
								   </div>
								   <div class="col-sm-2 col_paddingtop">
            					  </div>
								</div>
												  
							</div>
							
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
<script src="<?php echo $this->baseUrl('public/js/settings.js');?>"></script>
<script>
function AssignTofck(){
 var oEditor = FCKeditorAPI.GetInstance('FCKeditor1');

 var fieldvalue = $('#dynamic_field').val();

 oEditor.InsertHtml(fieldvalue);

}
</script>