<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
                <?=$this->ModelObj->tabNavigation(); ?>
              </ul>
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-1">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Accounting Function')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-2 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede">
						<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Accountsetting','action'=>'addeditaccountingfunction'),'default',true)?>?mode=add','30%','50%');"> <i class="fa fa-plus-square"></i><?php echo $this->translate('Add New Function')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('Function Number');?></th>
								<th><?=$this->translate('Decription');?> </th>
								 
								<th><?=$this->translate('Status');?></th>
								 
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->AccountingFunction)>0){
						 foreach($this->AccountingFunction as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
                        <td width="10%" data-label="Function Number"><?php echo $key; ?></td> 
						<td width="10%" data-label="Decription"><?php echo $data['description']; ?></td>
						 
						   
						<td width="10%"><span class="cell" data-label="Status" id="statusSpan_<?=$key?>" ><?php if($data['status'] == "1") {  ?><img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=AccountingFunction?>','Status','0','function_id','<?=$data['function_id']?>','<?=$key?>');" title="Change Status into In-Active" class="changeStatus" />
						<?php } else { ?>
						<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=AccountingFunction?>','Status','1','function_id','<?=$data['function_id']?>','<?=$key?>');" title="Change Status into Active" class="changeStatus" />
						<?php } ?>
						</span></td>
						
						 
						<td width="10%" data-label="Action">
						 		<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Accountsetting','action'=>'addeditaccountingfunction'),'default',true).'?mode=edit&id='.$data['function_id']?>','30%','50%');"> 
						 			<i class="fa fa-edit fa-2x"></i>
								</a>
						
                        </td>  
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>