<form action="" method="post" name="addrouting" class="inputbox" >
<input type="hidden" id="user_id" value="<?php echo $this->Request['user_id'];?>">
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6><?php echo $this->translate("Add Routing");?></h6>
          </div>
          <div class="row">
            <div class="col-sm-4 col_paddingtop">
			 <label><?php echo $this->translate("Country"); ?></label>
				 <select name="country_id" id="country_id" class="inputfield"  style="margin-left: 0px;">
				<?php foreach($this->countrylist as $countrylist){
				  $selected = '';
				  if(isset($this->Request['country_id']) && $countrylist['id']==$this->Request['country_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $countrylist['id']?>" <?php echo $selected;?>><?php echo $countrylist['country_name']?></option>
				<?php } ?>
              </select>
            </div>
   <div class="clearfix"></div>
   
   <?php foreach($this->weightclass as $key=>$weightclass){
     if($key==0){?>
		<div class="col-sm-3 col_paddingtop">
		<label><?php echo $this->translate("Weight Class"); ?></label>
		<input type="text" readonly="readonly" name="routing[<?php echo $weightclass['class_id'];?>][class_id]" value="<?php echo $weightclass['min_weight'].'- '.$weightclass['max_weight'];?>" class="inputfield">
		 
		</div>
		<div class="col-sm-2 col_paddingtop">
		<label><?php echo $this->translate("Depot Price"); ?></label>
		<input type="text" name="routing[<?php echo $weightclass['class_id'];?>][depot_price]" id="depot_price" class="inputfield">
		</div>
		<div class="col-sm-3 col_paddingtop">
		<label><?php echo $this->translate("Remark"); ?></label>
		<input type="text" name="routing[<?php echo $weightclass['class_id'];?>][remark]" id="remark" class="inputfield">
		</div>
		<div class="clearfix"></div>
	 <?php } else{?>
	    <div class="col-sm-3 col_paddingtop">
		<input type="text" readonly="readonly" name="routing[<?php echo $weightclass['class_id'];?>][class_id]" value="<?php echo $weightclass['min_weight'].'- '.$weightclass['max_weight'];?>" class="inputfield">
		</div>
		<div class="col-sm-2 col_paddingtop">
		<input type="text" name="routing[<?php echo $weightclass['class_id'];?>][depot_price]" id="depot_price" class="inputfield">
		</div>
		<div class="col-sm-3 col_paddingtop">
		<input type="text" name="routing[<?php echo $weightclass['class_id'];?>][remark]" id="remark" class="inputfield">
		</div>
		<div class="clearfix"></div>	
   <?php  }} ?>
   <div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
     
	  <div class="col-sm-2 col_paddingtop"> <input type="submit" name="submit" value="Add Routing" class="btn btn-danger btn-round"></div>
   </div>
</div>
</div>
</form>
<script>

</script>