

		<div class="input-title"><?php echo $this->translate("New Mail/Post")?></div>
	
		<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
          <div class="col-sm-12">
	<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

			<form method="post" action="" id="maillist" name="maillist">
						
				<div id="tablegrid">
					<table width="100%" border="0" id="example">
					    <thead>
						<tr><td colspan="8" style="text-align:left">
						  <select name="manifest_action" id="manifest_action" class="inputfield" style="width:20%" onchange="((this.value==2 && confirm('Are you sure, want to delete this item')) || this.value==1)?$('#maillist').submit():''">
							  <option value=""><?=$this->translate('Select');?></option>
							  <option value="1"><?=$this->translate('Print Manifest');?></option>
							  <option value="2"><?=$this->translate('Delete');?></option>
						 </select>
						</td></tr>
						<tr>
							<th>#</th>
							<th><?=$this->translate('Manifest No.');?></th>
							<th><?=$this->translate('Customer');?> </th>
							<th><?=$this->translate('Quantity');?></th>
							<th><?=$this->translate('Price');?></th>
							<th><?=$this->translate('Create Date');?></th>
							<th><?=$this->translate('Pickup');?></th>
							<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						
						<tbody>
						<?php
						if(count($this->records)>0){
							$i=0;
						 	foreach($this->records as $index=>$data){
						 	$class = ($i%2==0)?'even':'odd'; ?>
							<tr class="<?php echo $class;?>">
								<td><input type="checkbox" name="manifest_number[]" value="<?php echo $data['manifest_number']; ?>"></td> 
								<td data-label="Manifest No."><?php echo $data['manifest_number']; ?></td> 
								<td data-label="Customer"><?php echo $data['company_name']; ?></td>
								<td data-label="Quantity"><?php echo $data['total_quantity']; ?></td> 
								<td  data-label="Price"><?php echo $data['total_price']; ?></td> 
								<td data-label="Create Date"><?php echo commonfunction::TimeFormat($data['create_date']); ?></td> 
								<td data-label="Pickup Status"><?=commonfunction::PickupSatus($data['assigned_date'],$data['pickup_status'])?></td> 
								<td data-label="Action">
									<a href="<?=$this->url(array('controller'=>'Mailshipment','action'=>'editmailpost'),'default',  true).'?mail_id='.Zend_Encript_Encription::encode($data['mail_id'])?>"><i class="fa fa-edit" title="<?php echo $this->translate("Edit Mail Post");?>" ></i></a>&nbsp;|&nbsp;
							 <img src="<?=IMAGE_LINK.'/print.png'?>" title="<?php echo $this->translate("Print");?>" onclick="Manifestaction('<?php echo $data['manifest_number']?>','Print')" />&nbsp;|&nbsp;
							 <img src="<?=IMAGE_LINK.'/delete.png'?>" title="<?php echo $this->translate("Delete Shipment");?>" onclick="if(confirm('Are you sure, you want to delete this?')){Manifestaction('<?php echo $data['manifest_number']?>','Delete')}"/>
								</td> 
							</tr>
						<?php $i++;}} else{ ?>
						<tr>
						 <td></td><td></td><td></td> <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td><td></td><td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>
                     </table>
						
				</div>
			</form>	
			</div></div></div>
			</div>
		
	
	<script>
    
	$(document).ready(function() {
	  $('#example').DataTable();
	 //$('div.dataTables_filter input').addClass('inputfield');
	} );
	function Manifestaction(manifest_number,actions){
	   $.ajax({
		 type :'post',
		 url: '<?php echo $this->url(array('controller'=>'Mailshipment','action'=>'printmanifest'),'default',true)?>',
		 data: 'manifest_number='+manifest_number+'&actions='+actions+'&ajax=1',
		 dataType : 'json',
		 success:function(response){ //alert(response);
			  if(response.status==1 && actions=='Print'){
			     window.open(response.message);
			  }else if(response.status==1 && actions=='Delete'){
			     window.location.reload();
			  }
			} 
		 });
	}
	</script>