
<style>
.input_text{border: 1px solid #ccc;
    box-shadow: 0 1px 3px #ddd inset;
    box-sizing: border-box;
    display: inline-block;
    padding: 5px 10px;
    font-size: 15px;
    width: 100%;
    color: #000000;}
</style>
<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="filter_form" name="filter_form">
		<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-3 col_paddingtop">
				<label><?php echo $this->translate("Country");?></label>
				<select name="country_id" id="country_id" class="inputfield" style="width:60%">
			    <option value="">--<?php echo $this->translate("Country"); ?>--</option>
				<?php foreach($this->countrylist as $countrylist){
				  $selected = '';
				  if(isset($this->Request['country_id']) && $countrylist['id']==$this->Request['country_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $countrylist['id']?>" <?php echo $selected;?>><?php echo $countrylist['country_name']?></option>
				<?php } ?>
              </select>
				</div>
				<div class="col-sm-3 col_paddingtop">
				<label><?php echo $this->translate("Weight Class");?></label>
				<select name="weight_class_id" id="weight_class_id" class="inputfield" style="width:50%">
			    <option value="">--<?php echo $this->translate("Weight Class"); ?>--</option>
				<?php foreach($this->weightclass as $weightclass){
				  $selected = '';
				  if(isset($this->Request['weight_class_id']) && $weightclass['class_id']==$this->Request['weight_class_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $weightclass['class_id']?>" <?php echo $selected;?>><?php echo $weightclass['min_weight'].' - '.$weightclass['max_weight']?></option>
				<?php } ?>
              </select>
				</div>
				<?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11){?>
				<div class="col-sm-4 col_paddingtop">
				<label><?php echo $this->translate("Depot");?></label>
				<select name="user_id" id="user_id" class="inputfield" style="width:60%">
			    <option value="">--<?php echo $this->translate("Select"); ?>--</option>
				<?php foreach($this->depotlist as $depotlist){
				  $selected = '';
				  if(isset($this->Request['user_id']) && $depotlist['user_id']==$this->Request['user_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $depotlist['user_id']?>" <?php echo $selected;?>><?php echo $depotlist['company_name']?></option>
				<?php } ?>
              </select>
				</div>
				<?php } ?>
				<div class="col-sm-2 col_paddingtop"> <input type="submit" name="submit" value="Search" class="btn btn-danger btn-round"></div>
				<div class="col-sm-12 col_paddingtop"></div>
				</div>
		 <?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11){?>		
			<div class="clear-all"></div>
			  &nbsp;&nbsp;<a href="javascript:void(0);" onclick="Addrouting()"><i class="fa fa-plus-square"></i><?php echo $this->translate("Add Routing");?></a>
			</div>
		<?php } ?>	
		<!-- end filter -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
				<div id="table">
					<div class="header-row row"> 
					<span class="cell"><?php echo $this->translate("Depot Name");?></span> 
					<span class="cell"><?php echo $this->translate("Country");?></span> 
					<span class="cell"><?php echo $this->translate("Weight Class");?></span>
					<span class="cell"><?php echo ($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11)?$this->translate("Depot Price"):$this->translate("Customer Price");?></span> 
					<span class="cell"><?php echo $this->translate("Remark");?></span> 
					<span class="cell"><?php echo $this->translate("Action");?></span>				
					</div>
					<?php if(count($this->records)>0){
						foreach($this->records as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" data-label="Depot"><?=$data['company_name'];?></span>
							<span class="cell" data-label="Country"><?=$data['country_name']?></span>
							<span class="cell" data-label="Weight Class"><?= $data['min_weight'].'-'.$data['max_weight']?></span>
							<span class="cell" data-label="Price">
							<?php $price =($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11)?$data['depot_price']:$data['customer_price'];
							?>
							<span id="display_price_<?php echo $data['mail_routing_id'];?>" ><?php echo $price;?></span>
							<input type="text" name="price_<?php echo $data['mail_routing_id'];?>" class="input_text" id="price_<?php echo $data['mail_routing_id'];?>"  value="<?php echo $price;?>" style="display:none;width:50%"/></span>
							<span class="cell" data-label="Remark">
							<span id="display_remark_<?php echo $data['mail_routing_id'];?>" ><?=$data['remark']?></span>
							<input type="text" name="remark_<?php echo $data['mail_routing_id'];?>"  class="input_text" id="remark_<?php echo $data['mail_routing_id'];?>"  value="<?=$data['remark']?>" style="display:none;width:50%" <?php echo ($this->ModelObj->Useconfig['level_id']!=1 && $this->ModelObj->Useconfig['level_id']!=11)?'disabled="disabled"':''?>/></span>
							</span>
							<span class="cell" data-label="Action">
							 
							
							<a href="javascript:void(0);" id="edit_action_<?php echo $data['mail_routing_id'];?>"  onclick="editrouting('<?php echo $data['mail_routing_id'];?>')" title="Edit"><i class="fa fa-edit fa-2x"></i></a>
							<a href="javascript:void(0);" id="update_action_<?php echo $data['mail_routing_id'];?>"  onclick="updaterouting('<?php echo $data['mail_routing_id'];?>','update')" title="Update" style="display:none"><i class="fa fa-refresh fa-2x"></i></a>
							 <?php if($this->ModelObj->Useconfig['level_id']==1 || $this->ModelObj->Useconfig['level_id']==11){?>
							 &nbsp;|&nbsp;
							 
							
							 <a href="javascript:void(0);"  onclick="if(confirm('Are you sure you want to delete this?')){updaterouting('<?php echo $data['mail_routing_id'];?>','delete')}else{return false;}" title="Delete"><i class="fa fa-remove fa-2x"></i></a>
							  <?php }?>
							 </span>
						</div>
					<?php }}else{?>
						
						<div class="row odd">
							<span class="cell" colspan="6"><b><?=$this->translate("Recod not found !");?></b></span> 
						</div>
					<?php }?>	

				</div>
					 	
			</form>	
			</div></div></div>
<script>
function Addrouting(){
   var user_id = $('#user_id').val();
   if(user_id>0){
       openbox('<?php echo $this->url(array('controller'=>'Mailshipment','action'=>'addmailrouting'),'default',true);?>?user_id='+user_id,'70%','90%');
   }else{
     alert('Please select Depot first');return false;
   }
}
function editrouting(routing_id){
   $('#price_'+routing_id).show();
   $('#remark_'+routing_id).show();
   $('#display_price_'+routing_id).hide();
   $('#display_remark_'+routing_id).hide();
   $('#edit_action_'+routing_id).hide();
   $('#update_action_'+routing_id).show();
}

function updaterouting(routing_id,mode){
   var price = $('#price_'+routing_id).val();
   var remark = $('#remark_'+routing_id).val();
   $.ajax({
      type: 'Post',
	  url : '<?php echo $this->url(array('controller'=>'Mailshipment','action'=>'routingupdate'),'default',true);?>',
	  data: 'mail_routing_id='+routing_id+'&price='+price+'&remark='+remark+'&mode='+mode,
	  success: function(msg){
	    if(msg=='U'){
			$('#price_'+routing_id).hide();
			$('#remark_'+routing_id).hide();
			$('#display_price_'+routing_id).html(price);
			$('#display_remark_'+routing_id).html(remark);
			$('#display_price_'+routing_id).show();
			$('#display_remark_'+routing_id).show();
			$('#edit_action_'+routing_id).show();
			$('#update_action_'+routing_id).hide();
		}else{
		  location.reload();
		}
	  }
   });
}

</script>			