
<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="manifest" name="manifest">
		<!-- filter start -->
			<!-- filter start -->
			<div class="filter">
				<div class="input-title"><?php echo $this->translate("Search");?></div>
				<div class="row row_nopadding decor-success" style="margin-left:0px !important;margin-right:0px !important;">
				<div class="clear-all"></div>
				<div class="col-sm-3 col_paddingtop">
				<label><?php echo $this->translate("Forwarder");?></label>
				<select name="forwarder_id" id="forwarder_id" class="inputfield" style="width:60%">
			    <option value="">--<?php echo $this->translate("Forwarder"); ?>--</option>
				<?php foreach($this->forwarder as $forwarder){
				  $selected = '';
				  if(isset($this->Request['forwarder_id']) && $forwarder['forwarder_id']==$this->Request['forwarder_id']){
				    $selected = 'selected="selected"';
				  }?>
				  <option value="<?php echo $forwarder['forwarder_id']?>" <?php echo $selected;?>><?php echo $forwarder['forwarder_name']?></option>
				<?php } ?>
              </select>
				</div>
				<div class="col-sm-3 col_paddingtop">
				  <label><?php echo $this->translate("From Date");?></label>
					<input type="text" name="from_date" id="from_date" value="<?php echo (isset($this->Request['from_date'])?$this->Request['from_date']:'')?>"  class="inputfield" style="width:60%">
				  </div>
				<div class="col-sm-3 col_paddingtop">
				  <label><?php echo $this->translate("To Date");?></label>
				  <input type="text" name="to_date" id="to_date" value="<?php echo (isset($this->Request['to_date'])?$this->Request['to_date']:'')?>"  class="inputfield" style="width:60%">
				</div>
				<div class="col-sm-2 col_paddingtop">
				  <button class="btn btn-danger btn-round" name="search" type="submit" value="Search"><?php echo $this->translate("Search");?></button>
				</div>
				<div class="clear-all"></div>
				
				<div class="col-sm-12 col_paddingtop"></div>
				</div>
		</div>
		<!-- end filter -->
		<!-- end filter -->
		
		<div class="b-email-list ac-custom ac-checkbox ac-checkmark" autocomplete="off">
						
				<div id="table">
					<div class="header-row row"> 
						<span class="cell"><?php echo $this->translate("Forwarder Name");?></span> 
						<span class="cell"><?php echo $this->translate("Edi");?></span> 
						<span class="cell"><?php echo $this->translate("Create Date");?></span> 
						<span class="cell"><?php echo $this->translate("Upload Status");?></span> 
						<span class="cell"><?php echo $this->translate("Download EDI");?></span> 
						<span class="cell"><?php echo $this->translate("View Manifest");?></span>
						<span class="cell"><?php echo $this->translate("Re-Upload");?></span>
						<span class="cell"><?php echo $this->translate("Action");?></span>
					</div>
					<?php 
					if($this->records['Total']>0){
						foreach($this->records['Records'] as $index=>$data){
							$class = (($index)%2==0) ? 'class="row odd"' :'class="row even"';?>
						<div <?=$class?>>
							<span class="cell" data-label="Forwarder Name"><?=$data['forwarder_name'];?></span>
							<span class="cell" data-label="EDI File"><?=$data['edi_file_name'];?></span>
							<span class="cell" data-label="Create Date"><?=commonfunction::TimeFormat($data['create_date']);?></span>
							<span class="cell" data-label="Upload Status"><img src="<?=($data['upload_status']=='1')?IMAGE_LINK.'/icon_active.gif':IMAGE_LINK.'/icon_inactive.gif';?>"></span>
							<span class="cell" data-label="Download"><a href="<?php echo $this->url(array('controller'=>'Edimanager','action'=>'ediupdown'),'default',true).'?file_name='.date('Y_m',strtotime($data['create_date'])).'/'.$data['edi_file_name'].'&mode=Download&forwarder='.$data['forwarder_id']?>"><i class="fa fa-download fa-2x" title="<?php echo $this->translate("Download");?>"></i></a></span>
							<span class="cell" data-label="Manifest"><a target="_blank" href="<?=FORWARDER_MANIFEST_OPEN.date('Y_m',strtotime($data['create_date'])).'/'.$data['manifest_file_name'];?>"><i class="fa fa-eye fa-2x" title="<?php echo $this->translate("View Manifest");?>"></i></a></span>
							<span class="cell" data-label="Re-Upload"><a href="<?php echo $this->url(array('controller'=>'Edimanager','action'=>'ediupdown'),'default',true).'?file_name='.date('Y_m',strtotime($data['create_date'])).'/'.$data['edi_file_name'].'&mode=Upload&forwarder='.$data['forwarder_id']?>"><i class="fa fa-upload fa-2x" title="<?php echo $this->translate("Upload");?>"></i></a></span>
							<span class="cell" data-label="Action">
							
							</span>
						</div>
					<?php } }else{ ?>
					<span class="cell" data-label="No Record"><?php echo $this->translate("No Record found!");?></span>
					<?php  }  ?>
				</div>
					 	
			</div>
			</form>	
			</div></div>
<script>
$(function() {
		$( "#from_date" ).datepicker({
		  dateFormat: 'yy-mm-dd',
		  showOtherMonths: true,
		  selectOtherMonths: true
		});
		$( "#to_date" ).datepicker({
		  dateFormat: 'yy-mm-dd',
		  showOtherMonths: true,
		  selectOtherMonths: true
		});
	
	});
</script>			