<?php $form = $this->AddPortForm; ?>
<form action="" method="post" name="addcountry" class="inputbox" >
<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
          <div class="b-email-title">
            <h6>Add New Port</h6>
          </div>
          <div class="row">
			<div class="col-sm-6 col_paddingtop">
              <?php echo $form->country_id; ?>
            </div>
			<div class="col-sm-6 col_paddingtop">
            </div>
            <div class="clearfix"></div>
			<div id='addmore_1' class="addmore">
            	<div class="col-sm-6 col_paddingtop">
			  	<?php echo $form->port_name; ?>
            	</div>
            	<div class="col-sm-6 col_paddingtop">
			  	<?php echo $form->port_code; ?>
			 	</div>
			 	<!--<div class="col-sm-2 col_paddingtop" style="margin-top:25px;">
				<img src="<?=IMAGE_LINK?>/addmore.gif" />
            	</div>-->
			</div>
			<div class="clearfix"></div>
			<div class="col-sm-10 col_paddingtop">
            </div>
            <div class="col-sm-2 col_paddingtop"> <?php echo $form->submit; ?> </div>
            </div>
          </div>
        </div>
</form>

