<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
				<?=$this->ModelObj->tabNavigation(); ?>
              </ul>
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-7">
					<form method="post" name= "blockip_form">
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Block Ip LIst')?></div>
					  <div class="clear-all"></div>
						<div class="col-sm-3 col_paddingx10"> <span class="input input--kaede input--filled">
						<input name="block_ip" id="block_ip" required pattern="((^|\.)((25[0-5])|(2[0-4]\d)|(1\d\d)|([1-9]?\d))){4}$" value="" class="input__field input__field--kaede" placeholder="Enter Block Ip" type="text">
						<label for="block_ip" class="input__label input__label--kaede"> <span class="input__label-content input__label-content--kaede">Add Block Ip </span> </label>
						</span> </div>
					  <div class="col-sm-3 col_paddingx10">
						<input class="btn btn-danger btn-round" name="submit" value="submit" type="submit"/>
					  </div>
					  <div class="col-sm-6 col_paddingx10">
					  </div>
					</div>
             
					 <div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('S.No.');?></th>
								<th><?=$this->translate('Blocked Ip');?> </th>
								<th><?=$this->translate('Added Date');?></th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->blockipList)>0){
						 foreach($this->blockipList as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
						<td width="20%" data-label="Serial No."><?php echo $key+1; ?></td>
                        <td width="30%"  data-label="IP Address"><?php echo $data['block_ip']; ?></td> 
						<td width="40%"  data-label="Created Date"><?php echo $data['created_date']; ?></td>
						<td width="10%" class="cell breadcrumb"><li><a href="javascript:void(0);" onClick="deleterecord('<?=BLOCKIP?>','is_delete','1','id','<?=$data['id']?>');"><i class="fa fa-trash"></i></a> </li></td> 
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
                
				</form>
			  </div>
			 </div>
			 </div>
			 </div>
            </div>
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>