<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/timepicker/jquery.ui.timepicker.css')?>">
<script src="<?php echo $this->baseUrl('/public/timepicker/include/ui-1.10.0/jquery.ui.widget.min.js')?>"></script>
<script src="<?php echo $this->baseUrl('/public/timepicker/jquery.ui.timepicker.js')?>"></script>

	<div class="row row-broken">
        <div class="col-sm-12">
			<div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
				<?=$this->ModelObj->tabNavigation(); ?>
              </ul>
			  
				<div class="tab-content">
					<div class="tab-pane fade in active" id="tab-5">
						<div class="col-inside-lg decor-default">
             	  
							<div class="row tab-filter row_nopadding decor-success tab-position">
							  <div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
								  <div class="b-email-title">
									<h6>Edit Packet Shop</h6>
								  </div>
								  <div class="row" style="padding-right:40px;">
										<?php echo $this->editPacketShop; ?>
								  </div>
								</div>				  
							</div>
							
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
<script src="<?php echo $this->baseUrl('public/js/settings.js');?>"></script>