<div id="table"><div class="header-row row">
		<span class="cell" style="text-align:left"><?php echo $this->translate("Edit Forwarder");?></span> 
	</div></div>
	
	<div class="col-md-2"></div>
		<div class="col-md-8">
			<div id="table"><div class="header-row row">
	</div>
	
	</div>		
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1"  style="display: table-cell;">
					<?php echo $this->editForwarder; ?>
				</div>
			</div>
		</div>
	<div class="col-md-2"></div>