<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
			  	<?=$this->ModelObj->tabNavigation(); ?>
              </ul>
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-5">
				 	<div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="clear-all"></div>
					  <div class="col-sm-3 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="<?=$this->url(array('controller'=>'Settings','action'=>'addpacketshop'),'default',  true)?>"> <img src="<?=IMAGE_LINK?>/addmore.gif" /> <?php echo $this->translate('Add New Packet Shop')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
                    <div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('S. No');?></th>
								 <th><?=$this->translate('Shope Name');?></th>
								  <th><?=$this->translate('Country');?> </th>
								  <th><?=$this->translate('Postal Code');?></th>
								   <th><?=$this->translate('City');?></th>
									<th><?=$this->translate('Address');?></th>
									<th><?=$this->translate('Working Hours');?></th>
									 <th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->paketshops)>0){
						 foreach($this->paketshops as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr class="<?php echo $class;?>">
						<td width="5%" data-label="Serial No."><?php echo $key+1; ?></td>
                        <td width="20%" data-label="Shop NAme"><?php echo $data['shope_name']; ?></td> 
						<td width="10%" data-label="Country"><?php echo $data['country']; ?></td>
						<td width="10%" data-label="Postal Code"><?php echo $data['postal_code']; ?></td> 
						<td width="10%" data-label="City Name"><?php echo $data['city']; ?></td> 
						<td width="20%" data-label="address"><?php echo $data['address']; ?></td>
						<td width="15%" data-label="Working Days"><a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'shopdays'),'default',  true).'?id='.Zend_Encript_Encription:: encode($data['id'])?>','60%','71%');">
						<?php echo $this->translate('Working Days')?></a></td>
						<td width="10%" data-label="Action"><a href="<?=$this->url(array('controller'=>'Settings','action'=>'editpacketshop'),'default',  true).'?id='.Zend_Encript_Encription:: encode($data['id'])?>"><i class="fa fa-edit"></i></a>
						
						<a href="javascript:void(0);" onClick="deleterecord('<?=PARCELSHOP?>','is_delete','1','id','<?=$data['id']?>');"><i class="fa fa-trash"></i></a>
						</td>
					</tr>
						<?php }} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
                    
               
					</div>
                </div>
			  </div>
			 </div>
            </div>
 
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>