	<div class="row row-broken">
        <div class="col-sm-12">
			<div class="tabs" id="seventh-tabs">
			  <ul class="nav nav-tabs nav-justified">
				<?=$this->ModelObj->tabNavigation(); ?>
              </ul>
				<div class="tab-content">
					<div class="tab-pane fade in active" id="tab-2">
						<div class="col-inside-lg decor-default">
             	  
							<div class="row tab-filter row_nopadding decor-success tab-position">
							  <div class="input-title">Print Level Setting</div>
							  <div class="clear-all"></div>
								<?php $form = $this->PrintSettingForm;
							  /*$form->setAttribute('action', $this->url('settings', array('action' => 'printsetting')));
							  $form->prepare();
							  echo $this->form()->openTag($form);*/ ?>
						<form action="" method="post" name="printsetting" class="inputbox" >
							<div class="col-lg-12 col-md-12 col-sm-12 b-email" style="background:#ffffff;">
							  <div class="row">
								  <?php echo $form->label_position; ?>
								<div class="clear-all"></div>
								<div class="col-sm-2 col_paddingtop">
								  <?php echo $form->submit; ?>
								</div>
								<div class="col-sm-10 col_paddingtop">
								</div>
								<div class="clear-all"></div>
								
							  </div>
							</div>
						</form>
							</div>
							
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
	<script>
	$(document).ready(function(){
   			$( ".control--radio" ).append('<div class="control__indicator"></div>');
	});
	</script>