<div class="row row-broken">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
			  
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab-6">
					<form>
					  <div class="row tab-filter row_nopadding decor-success tab-position">
					  <div class="input-title"><?php echo $this->translate('Services Setting')?></div>
					  <div class="clear-all"></div>
					  <div class="col-sm-3 col_paddingx10">
						<label for="input-2" class="input__label input__label--kaede"> 
						<span class="input input--kaede"><a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'addeditservice'),'default',  true).'?mode=addMain'?>','30%','75%');"> <img src="<?=IMAGE_LINK?>/addmore.gif" /> <?php echo $this->translate('Add New Service')?></a>
						</span></label>
					  </div>
					  <div class="col-sm-9 col_paddingx10"> <span class="input input--kaede"></span> 
						</div>
	
					</div>
					<div  id="tablegrid">
					 <table width="100%" border="0" id="dataTableGridId">
					    <thead>
						<tr>
								<th><?=$this->translate('S No.');?></th>
								<th><?=$this->translate('Service Name');?></th>
								<th><?=$this->translate('Code For Import Shipment');?> </th>
								<th><?=$this->translate('Status');?></th>
								<th><?=$this->translate('Action');?></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if(count($this->records)>0){
						$i = 0;
					 foreach($this->records as $key=>$data){
						 $class = ($key%2==0)?'even':'odd'; ?>
						<tr style="background: green;" class="<?php echo $class;?>">
						<td data-label="S.No."><?php echo $i = $i+1; ?></td> 
                        <td data-label="Service Name"><?php echo $data['service_name']; ?></td> 
						<td data-label="Code For Import Shipment"><?php echo $data['internal_code']; ?></td>
						<td><span class="cell" data-label="Status" id="statusSpan_<?=$i?>" ><?php if($data['status'] == "1") {  ?><img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=SERVICES?>','status','0','service_id','<?=$data['service_id']?>','<?=$i?>');" title="Change Status into In-Active" class="changeStatus" />
								<?php } else { ?>
								<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=SERVICES?>','status','1','service_id','<?=$data['service_id']?>','<?=$i?>');" title="Change Status into Active" class="changeStatus" />
								<?php } ?>
							</span>
						</td>
						<td data-label="Action">
						<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'addeditservice'),'default',  true).'?mode=editMain&id='.Zend_Encript_Encription:: encode($data[SERVICE_ID])?>','30%','75%');"> <i class="fa fa-edit" title="Edit Service"></i></a>
						|<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'transitdetail'),'default',true).'?id='.Zend_Encript_Encription:: encode($data[SERVICE_ID])?>','60%','90%');"><i class="fa fa-bus" title="Transit Detail" aria-hidden="true"></i></a>
						</td> 
					</tr>
						<?php
						  foreach($data['child'] as $subkey=>$addservice){
							 $class = ($key%2==0)?'even':'odd'; ?>
							<tr class="<?php echo $class;?>">
							<td data-label="S.No."><?php echo $i = $i+1; ?></td> 
							<td data-label="Service Name"><?php echo $addservice['service_name']; ?></td> 
							<td data-label="Code For Import Shipment"><?php echo $addservice['internal_code']; ?></td>
							<td>
							<span class="cell" data-label="Status" id="statusSpan_<?=$i?>" ><?php if($addservice['status'] == "1") {  ?><img src="<?=IMAGE_LINK?>/icon_active.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=SERVICES?>','status','0','service_id','<?=$addservice['service_id']?>','<?=$i?>');" title="Change Status into In-Active" class="changeStatus" />
								<?php } else { ?>
								<img src="<?=IMAGE_LINK?>/icon_inactive.gif" align="absmiddle" alt="Active" border="0" onclick="setStatus('<?=SERVICES?>','status','1','service_id','<?=$addservice['service_id']?>','<?=$i?>');" title="Change Status into Active" class="changeStatus" />
								<?php } ?>
								</span>
							</td>
							<td data-label="Action">
							<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'addeditservice'),'default',  true).'?mode=editMain&id='.Zend_Encript_Encription:: encode($addservice[SERVICE_ID])?>','30%','75%');"> <i class="fa fa-edit" title="Edit Service"></i></a>
							|<a href="javascript:void(0);" onclick="openbox('<?=$this->url(array('controller'=>'Settings','action'=>'transitdetail'),'default',true).'?id='.Zend_Encript_Encription:: encode($addservice[SERVICE_ID])?>','60%','90%');"><i class="fa fa-bus" title="Transit Detail" aria-hidden="true"></i></a>
							</td> 
					     </tr>
						<?php }
							}} else{ ?>
						<tr>
						  <td data-label="No Data"><div class="nodatatxt"><?=$this->translate('No Record Found!...')?></div></td>
						  <td></td><td></td><td></td><td></td>
						  </tr>
						<?php }
						?></tbody>

                     </table>
                    </div>
					
					 </form>
					</div>
                </div>
					<div>
			  </div>
			 </div>
            </div>
          </div>
<script>
$(document).ready(function() {
	 commonDataTableView()
} );
</script>