
	<div class="input-title"><?php echo $this->translate("Privilege Management")?></div>
		
		<div class="row row-broken" style="margin-left:0px !important;margin-right:0px !important;">
          <div class="col-sm-12">
            <div class="tabs" id="seventh-tabs">
              <!--<ul class="nav nav-tabs nav-justified">
                <li class="active"> <a href=""><?php echo $this->translate("List ")?><i class="fa fa-folder"></i></a> </li>
                <li> <a href=""><?php echo $this->translate("Add Privilege ")?><i class="fa fa-ticket"></i></a> </li>
              </ul>-->
	  

	<div class="tab-content">
		 <div class="tab-pane fade in active" id="tab-1">

		<form method="post" action="" id="privilegeform" name="privilegeform">
					
				<div id="tablegrid">
					 
					 <table width="100%" border="0" id="example">
					    <thead>
						<tr>
							<th width="20%" style="text-align:left"><?=$this->translate('Level of System User');?></th>
							<th width="80%" style="text-align:left"><?=$this->translate('Privilege Main Modules');?></th>
						</tr>
						</thead>
						
						<tbody>
							<?php if(count($this->privileges['UserLevel'])>0){ 
								$i=0;
								foreach($this->privileges['UserLevel'] as $leveldata){ 
									$class = ($i%2==0) ? 'even' : 'odd'; ?>
									<tr class="<?php echo $class;?>">
										<td data-label="Action" style="text-align:left">
											<a href='<?=$this->url(array('controller'=>'Privilege','action'=>'view'),'default',  true).'?token='.Zend_Encript_Encription:: encode($leveldata['level_id'])?>','60%','40%';"><?php echo $leveldata['levelName'] ?></a>
										</td>
										<td style="text-align:left">
											<?php foreach($this->privileges['LevelMainModule'][$leveldata['level_id']] as $index=>$module){
												$arrow = ((count($this->privileges['LevelMainModule'][$leveldata['level_id']])-$index)>1) ? " &rsaquo;&rsaquo; " : '';
												
												echo $module['module_name'].$arrow;
												}
												if(count($this->privileges['LevelMainModule'][$leveldata['level_id']])>0){ ?> 
													<a href='<?=$this->url(array('controller'=>'Privilege','action'=>'view'),'default',  true).'?token='.Zend_Encript_Encription:: encode($leveldata['level_id'])?>','60%','40%';"><?=$this->translate('[See All Modules]');?></a>
											<?php  } ?>
										</td>
									</tr>
							<?php $i++; } } ?>
							</tbody>
                     	</table>
					</div>
				</form>	
				</div>
			</div>
		</div>
	</div>
</div>	

<script>
$(document).ready(function() {
  $('#example').DataTable({
  "pageLength": 10,
  "lengthMenu": [[10, 25, 50, 100, 200, 500, -1], [10, 25, 50, 100, 200, 500, "All"]],
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
       column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );

  });
</script>